### ISSUE TITLE
播放时的一个Bug

### ISSUE THREAD

**Issue by dowhilenet** [BrikerMan/BMPlayer#1]
你好很高兴你能开源这个库。最近我也在使用它。发现了一个小小的bug

在设置了`player.playWithURL()`之后，视频会自动的播放，但是呢播放按钮呢并不是暂停的按钮而是播放按钮。

![qq20160518-1](https://cloud.githubusercontent.com/assets/10379476/15362180/eb9b7b52-1d46-11e6-935a-281f620ff335.png)

**Comment by BrikerMan** [comment]
收到，等周末修复一下~

**Comment by BrikerMan** [comment]
已修复，明天同步至Cocoapods。可以先下载Example试试。
