### ISSUE TITLE
After I update BMPlayer，My video can`t play....

### ISSUE THREAD

**Issue by wenlanhuitai** [BrikerMan/BMPlayer#100]
**After I update BMPlayer，My video can`t play....**

**This is log ：**

| BMPlayerDelegate | loadedTimeDidChange | 95.9298222222222 of 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
loadedTimeDidChange - 100.573822222222 - 189.010422222222
| BMPlayerDelegate | loadedTimeDidChange | 100.573822222222 of 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
loadedTimeDidChange - 103.360222222222 - 189.010422222222
| BMPlayerDelegate | loadedTimeDidChange | 103.360222222222 of 189.010422222222

**///the player can not play ， but can buffer Buffer video：**

playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222
playTimeDidChange - 0.0 - 189.010422222222

**Comment by BrikerMan** [comment]
Are you updated to the release version? or the developing version?

**Comment by BrikerMan** [comment]
Please try with the latest 0.8.6 version ~

**Comment by wenlanhuitai** [comment]
thanks， I will try later .. 
Issue review：
this bug is not  one hundred percent，it  occur sometimes ：video is can not play,just buffering, but after buffered Still can not play。

but  sometimes it can play ..... 

I will  try new code version  again....

**Comment by BrikerMan** [comment]
Is that working?

**Comment by wwwjfy** [comment]
I met the same problem and rebooting the device fixed it. I think this might be a system bug. JFYI
