### ISSUE TITLE
Manual control loading indictator 

### ISSUE THREAD

**Issue by hunghn86** [BrikerMan/BMPlayer#102]
Please tell me how to control loadingIndector manually

I'm using BMPlayer. But loadingIndicator always showing. So, in viewdidload function
I want to stop it. But i can't do it.

**Comment by BrikerMan** [comment]
This might be a bug, please provide me with more detail, which version you are using?

**Comment by hunghn86** [comment]
Thanks for reply. I'm using BMPlayer 0.8.4

**Comment by BrikerMan** [comment]
Please help me try the latest developing version, by changing the pod file to
```
pod 'BMPlayer', :git => 'https://github.com/BrikerMan/BMPlayer.git'
```

**Comment by hunghn86** [comment]
Ok. I wil try and report result to you soon

**Comment by hunghn86** [comment]
I changed my pod file following your suggestion. But I still can not control loadingIndecator
Btw, in your Example: how can I call showLoader() and hideLoader() via BMCustomPlayer
Thank you

**Comment by BrikerMan** [comment]
May I have the url of video you are playing? I don't have the problem with the latest version, is that because the the [App Transport Security](http://stackoverflow.com/questions/30731785/how-do-i-load-an-http-url-with-app-transport-security-enabled-in-ios-9) ?

**Comment by hunghn86** [comment]
![simulator screen shot may 31 2017 5 34 19 am](https://cloud.githubusercontent.com/assets/23735535/26607906/e1441d08-45c2-11e7-9467-f82781455619.png)
Sorry for late reply. I've just taked a photo.
Actually I do not want to load any video when this screen display.
I will load video when user select row.
So when in viewWillAppear I want to hide the loading indicator of BMPlayer.
Could you please tell me how to hide it?

**Comment by BrikerMan** [comment]
Please check the example project. Here is one called `player - disallow autoplay`

**Comment by BrikerMan** [comment]
And coming to customize UI, here is still examples on Example project.
