### ISSUE TITLE
how play video local

### ISSUE THREAD

**Issue by kavoskhajavi** [BrikerMan/BMPlayer#103]
how play video local 

fun play(){

        let player = BMPlayer()
        view.addSubview(player)
        player.snp.makeConstraints { (make) in
            make.top.equalTo(self.view).offset(0)
            make.left.right.equalTo(self.view)
            // Note here, the aspect ratio 16:9 priority is lower than 1000 on the line, because the 4S iPhone aspect ratio is not 16:9
            make.height.equalTo(player.snp.width).multipliedBy(9.0/16.0).priority(750)
        }
        
        
        player.backBlock = { [unowned self] (isFullScreen) in
            if isFullScreen == true {
                return
            }

            
            self.dismiss(animated: true, completion: nil)
        }
        

        let url =  URL(string: "/Users/bfpig/Library/Developer/CoreSimulator/Devices/DD7090F6-57C3-43BD-8867-D4ED9DEF77B7/data/Containers/Data/Application/A35618EC-7DF0-45D4-97A3-2984377E7BF6/Documents/v1.mov")!
        player.playWithURL(url, title: "jj")
        
        player.autoPlay()
    
        self.view.layoutIfNeeded()

}

**Comment by BrikerMan** [comment]
Use this
``` 
let mydocpath = NSSearchPathForDirectoriesInDomains(FileManager.SearchPathDirectory.documentDirectory, FileManager.SearchPathDomainMask.userDomainMask, true)[0]
mydocpath.appending("/v1.mov")
```

**Comment by kavoskhajavi** [comment]
not play video

**Comment by fadylateef** [comment]
Any help !!!

**Comment by alfredolucomav** [comment]
+1
