### ISSUE TITLE
Unable to buffer HLS Cached Video in iOS 10 without internet connection.

### ISSUE THREAD

**Issue by venkateshcontus** [BrikerMan/BMPlayer#105]
I am using AVAsset download delegates to download M3u8 files and play it offline.However on playing offline video it needs internet to sync for buffering document files.if internet is active,within few second it buffers a document files.If the network is not available player gets stuck.Kindly help me to solve this issue.looking for a positive response from you.

**Comment by BrikerMan** [comment]
This is a bug of https://github.com/vitoziv/VIMediaCache which I used to cache video, I can't fix that now. Sorry about that.

**Comment by kushalhyperlink** [comment]
Hello Team 

The player couldn't play HLS format file. https://5a8ea362056bf.streamlock.net:1936/vod/smil:Elephants_dream.smil/playlist.m3u8

**Comment by birdmichael** [comment]
@kushalhyperlink 
hello.
The current progress is that the problem has been found.
This issue will be fixed in the near future.
Now consider whether to support HLS format caching.
If we need support to download files, create a local server to play.
The easiest way is to not support caching for streaming media.

**Comment by birdmichael** [comment]
@kushalhyperlink 
hello.
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=800000,NAME="360p",RESOLUTION=640x380
chunklist_w321565092_b800000_t64MzYwcA==.m3u8
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="spa",NAME="Espanol",DEFAULT=YES,URI="chunklist_w321565092_b128000_ao_slspa_t64RXNwYW5vbA==.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="eng",NAME="Ingles",DEFAULT=YES,URI="chunklist_w321565092_b128000_ao_sleng_t64SW5nbGVz.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=1200000,NAME="480p",RESOLUTION=854x480
chunklist_w321565092_b1200000_t64NDgwcA==.m3u8
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="spa",NAME="Espanol",DEFAULT=YES,URI="chunklist_w321565092_b128000_ao_slspa_t64RXNwYW5vbA==.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="eng",NAME="Ingles",DEFAULT=YES,URI="chunklist_w321565092_b128000_ao_sleng_t64SW5nbGVz.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=2000000,NAME="720p",RESOLUTION=1280x720
chunklist_w321565092_b2000000_t64NzIwcA==.m3u8
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="spa",NAME="Espanol",DEFAULT=YES,URI="chunklist_w321565092_b128000_ao_slspa_t64RXNwYW5vbA==.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="eng",NAME="Ingles",DEFAULT=YES,URI="chunklist_w321565092_b128000_ao_sleng_t64SW5nbGVz.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=4000000,NAME="1080p",RESOLUTION=1920x1080
chunklist_w321565092_b4000000_t64MTA4MHA=.m3u8
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="spa",NAME="Espanol",DEFAULT=YES,URI="chunklist_w321565092_b128000_ao_slspa_t64RXNwYW5vbA==.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="eng",NAME="Ingles",DEFAULT=YES,URI="chunklist_w321565092_b128000_ao_sleng_t64SW5nbGVz.m3u8"

```
This is the content of the file you provided. it is a Master Playlist.
But AVPlayer doesn't seem to support it by default, however it can be played in Safari.

There are two solutions now:
1. server. Split into different bit rates, different audio `ts` for you.
2. yourself. Then break it down into different `BMPlayerItems`. See if this link can help you.
https://github.com/M3U8Kit/M3U8Parser

**Comment by kushalhyperlink** [comment]
Hello Team, 

Thank you for the update. 
https://developer.apple.com/documentation/avfoundation/media_assets_playback_and_editing/using_avfoundation_to_play_and_persist_http_live_streams

I tried to use apple demo and check with my url and it works as expected and they have used  AVPlayer and AVURLAsset which BMPlayer used. 

[UsingAVFoundationToPlayAndPersistHTTPLiveStreams 2.zip](https://github.com/BrikerMan/BMPlayer/files/3999901/UsingAVFoundationToPlayAndPersistHTTPLiveStreams.2.zip)

**Comment by birdmichael** [comment]
@kushalhyperlink 
thx.
it's ok which BMPlayer used.
ur problem will be fixed in the near future.

**Comment by birdmichael** [comment]
@kushalhyperlink 
Sorry, it was my mistake.
m3u8 can be played. At that time, because my network was restricted, it could not be played during the test.
After subsequent verification, it can be played directly.
but We do not support automatic parsing of multiple audio tracks form Master Playlist.

> https://github.com/birdmichael/BMPlayer/commit/5511c44e721d1a7fc796c61bbe5048963ae6f63a
