### ISSUE TITLE
Remove the fullscreen button

### ISSUE THREAD

**Issue by MaxCavalheiro** [BrikerMan/BMPlayer#106]
Hello,
I'm trying remove the fullscreen button, but after do that I lost control (position and functionality) of progressView, timeSlider and totalTimeLabel, can you help me with this? I want just remove fullscreen button and make the totalTimeLabel and  progressView fill view inside mainMaskView, with right positions.

My Player:
![screen shot 2017-05-21 at 3 43 39 pm](https://cloud.githubusercontent.com/assets/2357618/26286454/590582f2-3e3c-11e7-96a4-a253611dc364.png)

**Comment by BrikerMan** [comment]
This might because you did not set the right constraint of the totalTimeLabel. You need to check you autolayout-constraints.

**Comment by MaxCavalheiro** [comment]
Thanks, I solved it, with another solution! thanks
