### ISSUE TITLE
How to seek player to Player's current time when different resolutions are chosen?

### ISSUE THREAD

**Issue by Karthikeyan1108** [BrikerMan/BMPlayer#107]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.
- [x] I have searched in [existing issues](https://github.com/BrikerMan/BMPlayer/issues?utf8=%E2%9C%93&q=) but did not find the same one.

## Installed with 
- [x] Cocoapods version 0.8.6

## Issue Description

Not possible to obtain the current time when switching the url.

I am playing hls streams and it has different bandwidths available for user to choose.If an user plays 240p for 30 seconds and switched to 360P the player is starting again.Expecting to keep the previous time of 240P to be the start time of 360P.

### Reproduce
Play the video.choose definitions.Play it for 20 seconds.Then try playing with another definition.

### Other Comment

[Add anything else here]

**Comment by BrikerMan** [comment]
Please complete the details. Thanks.

**Comment by Karthikeyan1108** [comment]
I have mentioned the details.please provide information on the same as soon as possible.Looking for a positive response from you.
Thanks
Karthikeyan.P

**Comment by BrikerMan** [comment]
Fixed, this is a bug. Please update the latest develop version to test. Will release new version soon.

```
pod 'BMPlayer', :git => 'https://github.com/BrikerMan/BMPlayer.git'
```

**Comment by Karthikeyan1108** [comment]
Thanks a lot.you saved my day !
