### ISSUE TITLE
first load the BMPlayer will autoplay,but i set the autoPlay is false.

### ISSUE THREAD

**Issue by HanXiaoTeng** [BrikerMan/BMPlayer#109]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.
- [x] I have searched in [existing issues](https://github.com/BrikerMan/BMPlayer/issues?utf8=%E2%9C%93&q=) but did not find the same one.

## Installed with 
- [x] Carthage
- [ ] Cocoapods

### What

[Tell us about the issue]

### Reproduce

[The steps to reproduce this issue. What is the URL you were trying to play, where did you put your code, etc.]

### Other Comment

[Add anything else here]

**Comment by BrikerMan** [comment]
You need to set the config before you init the player.
