### ISSUE TITLE
模拟器有声音 真机运行没声音

### ISSUE THREAD

**Issue by smalldu** [BrikerMan/BMPlayer#11]
能解答下么？着急。

**Comment by BrikerMan** [comment]
@smalldu 开静音开关了么？

**Comment by smalldu** [comment]
@BrikerMan  是的 ， 但是ZFPlayer 开着静音也能播放。。

**Comment by BrikerMan** [comment]
我没有做强制开音量，zf做了

smalldu <notifications@github.com>于2016年8月18日周四 下午7:20写道：

**Comment by smalldu** [comment]
@BrikerMan  好的，谢谢了，还有就是可否加上缓存 ，看过第二次打开再从头加载有点费流量。 可以加个属性 缓存开关的。

**Comment by BrikerMan** [comment]
@smalldu 缓存找空研究一下
