### ISSUE TITLE
Use of undeclared type"BMPlayerControlView"?

### ISSUE THREAD

**Issue by LGLee** [BrikerMan/BMPlayer#112]
cocoapods      BMPlayer ,

import Foundation
import BMPlayer
class MyPlayerView: BMPlayerControlView {
   }
error:Use of undeclared type "BMPlayerControlView"

**Comment by BrikerMan** [comment]
Which version you are using?

**Comment by LGLee** [comment]
pod 'BMPlayer'   
version is 0.7.1

**Comment by BrikerMan** [comment]
latest version is 0.8.7, please update~
