### ISSUE TITLE
How can I get the BMPlayerState

### ISSUE THREAD

**Issue by wsof401** [BrikerMan/BMPlayer#113]
The only way I found is the variable in `BMPlayerControlView`, but it is declared as `var`, not `open var`, so it can not be used, any solutions?

**Comment by BrikerMan** [comment]
You could access to this using delegate or block, just check the readme please.

**Comment by wsof401** [comment]
when the video play to the end,  the state delegate or block will invoke first, then the playing delegate or block invoke. So I have to customize a variable to save if played to the end.

the delegate or block should be used to observe the state changing,  It's weird to get state
