### ISSUE TITLE
How to change value of Pan to Seek 

### ISSUE THREAD

**Issue by lequanghuylc** [BrikerMan/BMPlayer#115]
Hello,

At first I'd like to thank you for your video player. I've recently discover this and it's amazing. 

It's just one small thing that I really want to customize is how to decrease the value of Pan to seek feature. When video is played, I just pan a little and it goes like a mile. I think a few seconds per small pan is better for UX.

So my question is:  How to change the value of Pan to Seek?

**Comment by BrikerMan** [comment]
Please try this out, if it works fine. I will release it later~.

```ruby
pod 'BMPlayer', :git => 'https://github.com/BrikerMan/BMPlayer.git'
```

**Comment by lequanghuylc** [comment]
Sorry for such a late response. It works like a charm. Thank you :D

I have a follow-up: can you show the value of Pan to Seek (second or minute) next to the seek time when user pans? I think it'll help because user  just seeks back a few seconds (to watch some great scene again or whatever) and when they pan they usually don't know the current time.

**Comment by BrikerMan** [comment]
If you need to change the UI of pan to seek, just subclass the `BMPlayerControlView` then override the function 
```swift
func showSeekToView(to toSecound: TimeInterval, total totalDuration:TimeInterval, isAdd: Bool)
```
Here is two example of customize UI in the demo project~ Try it out and feel free to contact me if you have any problem.
