### ISSUE TITLE
视频播放结束后，显示重播按钮的controlView，不进行操作，等几秒种后，controlView消失，就再也显示不出来了

### ISSUE THREAD

**Issue by ChaselAn** [BrikerMan/BMPlayer#116]
具体操作就是，播放视频，拖进度到最后，出现带有重播按钮的controlView，然后不进行任何操作，等待controlView自动消失，消失之后，再次点击视频，无任何反应，controlView就显示不出来了。如果只有controlView有返回按钮，就导致无法退出当前视频或者控制器。

**Comment by BrikerMan** [comment]
#108 在这里讨论播放结束的处理方式吧
