### ISSUE TITLE
Example 中的 Main.storyboard 中的 Video Play View Controller 怎样隐藏掉NavigationBar的

### ISSUE THREAD

**Issue by qixizhu** [BrikerMan/BMPlayer#118]
对着您的事例找了半天 ViewController 的设置，没有发现任何特殊的设置。

**Comment by BrikerMan** [comment]
修改该 controller 的 NavigationController 的这个属性
<img width="345" alt="qq20170609-145659 2x" src="https://user-images.githubusercontent.com/9368907/26964522-73b0f00e-4d24-11e7-8955-16630c41788c.png">

**Comment by qixizhu** [comment]
谢谢你，还真不容易发现啊。:)
