### ISSUE TITLE
Incompatible library version: BMPlayer requires version 1.0.0 or later, but SnapKit provides version 0.0.0

### ISSUE THREAD

**Issue by BackWorld** [BrikerMan/BMPlayer#119]
> Incompatible library version: BMPlayer requires version 1.0.0 or later, but SnapKit provides version 0.0.0

**Comment by BrikerMan** [comment]
please try with cocoapods~

**Comment by Senocico** [comment]
It is not possible to fix this issue for Carthage?

**Comment by ceeyang** [comment]
@Senocico   Hi, I met this problem to , did you fix it?

**Comment by TristenChenTao** [comment]
@Senocico Hi, @ceeyang  I met this problem to , did you fix it?

**Comment by ceeyang** [comment]
@TristenChenTao 

I use this framework with cocoapods:: `pod 'BMPlayer'` 
This framework depends on SnapKit, 
So, if you use carthage, and had used SnapKit, you should remove the SnapKit from the carthage.
Pod this framework will automatic add Snapkit to your Project.

By the way:
I had try anthor way to fix this bug without use cocoapods, but I failured.
I had to use carthage and cocoapods with my project.
If you find anthor way to solve it with carthage, please let me know, thanks.

**Comment by TristenChenTao** [comment]
@ceeyang  i use another framework ZFPlayer(https://github.com/renzifeng/ZFPlayer), it works.
ZFPlayer has no Carthage，so i also use cocoapods to integrate it。 

by the way:
ZFPlayer use oc language， so i do something extra work to use it in my swift project

**Comment by ceeyang** [comment]
@TristenChenTao 
I had tested using carthage build only one of  this framework,
It worked.
Maybe you can try remove the SnapKit from Carthage, add BMPlayer,
and rebuild again.

**Comment by ceeyang** [comment]
@TristenChenTao  That's great!

**Comment by TristenChenTao** [comment]
@ceeyang can you give me your tested demo, i try by your advice, but i fail
my email is TristenChenTao@qq.com

**Comment by ceeyang** [comment]
@TristenChenTao  I am sorry, I had tested it again, I found the last tested with wrong way, It's not worked. Forgive me.
