### ISSUE TITLE
视频比例不是16：9的时候出现bug

### ISSUE THREAD

**Issue by Tuluobo** [BrikerMan/BMPlayer#12]
我做的是手机屏幕录制，录出来的视频横屏的时候就会出现一半的效果，你的约束应该是对于设置的size中心对齐，宽高以最大的那个缩放，oc的项目也有这个问题。

**Comment by Tuluobo** [comment]
http://tuluobo-com.oss-cn-hangzhou.aliyuncs.com/20160825-163206.mp4
一个测试视频，可以测试一下。

**Comment by BrikerMan** [comment]
应该是 `AVLayerVideoGravity` 设置的问题，最新版本已支持修改该属性，你试试看看。

**Comment by BrikerMan** [comment]
@Tuluobo 给个反馈呗

**Comment by Tuluobo** [comment]
@BrikerMan 谢谢 嗯 是可以以正确使用了，前面主要用是的frame，修改成SnapKit设置就正常了。
