### ISSUE TITLE
*** Building scheme "BMPlayer" in BMPlayer.xcodeproj Build Failed

### ISSUE THREAD

**Issue by BackWorld** [BrikerMan/BMPlayer#120]
**<unknown>:0: error: no such file or directory: '/Users/zhuxuhong/Desktop/Demo/Carthage/Checkouts/BMPlayer/Source/BMPlayerManager.swift'**

**Comment by cookiebox33** [comment]
I have similar issue

**Comment by BrikerMan** [comment]
please try with cocoapods~

**Comment by BackWorld** [comment]
Why it is not supported to`Carthage` correctly?
