### ISSUE TITLE
Constant buffering in the demo

### ISSUE THREAD

**Issue by CaptainAlex** [BrikerMan/BMPlayer#126]
when i used your demo, i had constant buffering... no one video didnt load.
Can u help me? and can u say, is it player provide use youtube url?

**Comment by teefyy** [comment]
this player can be play  with  like  https?://xxx.com/(xxx.mp4|xxx.mp4|xxx.m3u8) etc..

**Comment by BrikerMan** [comment]
@teefyy Yes, it could play links like https?://xxx.com/(xxx.mp4|xxx.mp4|xxx.m3u8). @CaptainAlex Please check that if you could play the asset url in the browser, then provide me with more details.

**Comment by CaptainAlex** [comment]
@BrikerMan sorry )) i had a rest. Yes, i can play all url in the browser, but when i try your lib i have buffering...(

**Comment by CaptainAlex** [comment]
@BrikerMan  can u give me example with youtube url??? It would be awesome

**Comment by CaptainAlex** [comment]
@BrikerMan can u give me example with youtube url??? It would be awesome

**Comment by BrikerMan** [comment]
@CaptainAlex you will have to use the video url, not the youtube page url.
