### ISSUE TITLE
视频播放完成后bug

### ISSUE THREAD

**Issue by caoyunxiao** [BrikerMan/BMPlayer#128]
我发现在播放完成后，会出现一个重播按钮，这时候如果不做任何操作，等几秒钟它就会和进度条等控件一起隐藏，这时候去点击屏幕就无法显示了。

**Comment by caoyunxiao** [comment]
给出的demo同样有这个问题

**Comment by qinweizhao** [comment]
看源码发现，播放结束后，tap手势响应方法里面直接return，可以通过继承BMPlayerControlView，添加属性playerState,重写playerStateDidChange、onTapGestureTapped
override func playerStateDidChange(state: BMPlayerState) {
        super.playerStateDidChange(state: state)
        playerState = state
    }
    
    override func onTapGestureTapped(_ gesture: UITapGestureRecognizer) {
        super.onTapGestureTapped(gesture)
        if playerState == .playedToTheEnd {
            controlViewAnimation(isShow: !isMaskShowing)
        }
    }

**Comment by caoyunxiao** [comment]
我修改了代码，把return去掉了，还有个优化的地方就是，全屏的时候应该把播放器加载window上，退出全屏在还原，不然就会有很多问题存在，我本地改了。
