### ISSUE TITLE
NVActivityIndicatorView

### ISSUE THREAD

**Issue by s2339956** [BrikerMan/BMPlayer#130]
[!] Unable to satisfy the following requirements:

- `NVActivityIndicatorView (~> 3.6.0)` required by `Podfile`
- `NVActivityIndicatorView (= 2.10)` required by `BMPlayer (0.3.3)`

NVActivityIndicatorView 在 2.10 這版本會出現許多error
請問這有什麼解決辦法嗎！？

**Comment by BrikerMan** [comment]
现在的 BMPlayer 都 0.8.x 版本了，pod update 一下
