### ISSUE TITLE
Player loads when subtitle change

### ISSUE THREAD

**Issue by DipyaChandniDas** [BrikerMan/BMPlayer#134]
Hi All,

Thank you for providing this wonderful library.

There is an issue or behavior I must say which I marked is player load itself when we change the subtitle. Is there a way we just can change the subtitle without changing the video url. Currently while changing subtitle, we are using the below code 

            let str = URL(string: "new subtitle url")
            
            let url =  URL(string: "current video url")!
            
            let subtitle = BMSubtitles(url: str)
            
            let asset = BMPlayerResource(name: "Video Name Here",
                                         definitions: [BMPlayerResourceDefinition(url: url, definition: "")],
                                         cover: nil,
                                         subtitles: subtitle)
            
            
            player.setVideo(resource: asset)

This is loading the video and it seems like, its changing the track. Could you please help us on this.

**Comment by BrikerMan** [comment]
I have not considered that king situation which you need to change subtitle only. Will add a new function to do this later~

**Comment by DipyaChandniDas** [comment]
Hi @BrikerMan 

Could you please help us in doing this now then we would be very grateful to you.

**Comment by DipyaChandniDas** [comment]
Hi @BrikerMan 
There must be a way where we can just change the subtitle not the whole assets, I think this way we can get rid of the this reloading the video.

**Comment by BrikerMan** [comment]
You can do that by updating to the latest version, which is not released yet.
```swift
// remove subtile
delay(5, completion: {
    if let resource = self.player.currentResource {
        resource.subtitle = nil
    }
})
// or just replace, you don't have to remove first if you want to repleace
delay(10, completion: {
    if let resource = self.player.currentResource {
        resource.subtitle = BMSubtitles(url: Bundle.main.url(forResource: "SubtitleDemo2", withExtension: "srt")!)
    }
})
```

pod 'BMPlayer', :git => 'https://github.com/BrikerMan/BMPlayer.git'

**Comment by DipyaChandniDas** [comment]
HI @BrikerMan 
I have tried to change this however it does not seems to change.. I will add a point here, I am supporting WEB VTT and I am directly putting the subtitle url here directly from web.

**Comment by BrikerMan** [comment]
Please check the log and make sure the str file is downloadable.

**Comment by DipyaChandniDas** [comment]
Hi @BrikerMan 
Yes, its. if we reload the subtitle using the code which I previously given, its changing the subtitle.
I think, the new code you have given, is changing the subtitle however, track is not updated in AVPLayer so its playing the already provided AVAsset. We need to change the subtitle in AVAsset itself so that the text would change.

**Comment by BrikerMan** [comment]
I don't get. If you change the `BMSubtitles ` in the `BMPlayerResource`, the subtitle will be replaced in a second, just try out the demo. I have checked that.

**Comment by DipyaChandniDas** [comment]
@BrikerMan 
Is this because we are using the web resource, causing the issue because in the demo, you have used the local resource.

**Comment by BrikerMan** [comment]
Maybe, you could give me the src url for test

**Comment by DipyaChandniDas** [comment]
@BrikerMan 
Thank you for your support. We are able to solve this now.
One more thing remains is when we are making subtitle = nil, the last string of subtitle remain shown on the screen. Could you please help?

**Comment by BrikerMan** [comment]
update and try this
```swift
delay(5, completion: {
    if let resource = self.player.currentResource {
        resource.subtitle = nil
        self.player.forceReloadSubtile()
    }
})
```

**Comment by BrikerMan** [comment]
@DipyaChandniDas is that working?

**Comment by DipyaChandniDas** [comment]
Hi @BrikerMan 
Thank you yes, its working
