### ISSUE TITLE
How to detect error link play ?

### ISSUE THREAD

**Issue by MrLoveQD** [BrikerMan/BMPlayer#14]
Hi.
I'm using your library in my project to play video streaming. 
How can I detect that wrong link is played ?
I have a list link video, and i want auto play next link if current link is error.
Therefore, i want know when link is error.

Thank you so much.

**Comment by BrikerMan** [comment]
Added `BMPlayerDelegate`. Use this to detect status. When `status == BMPlayerState.error` you know here is an error.
