### ISSUE TITLE
请问我添加了选择音轨 为什么没有反应呢

### ISSUE THREAD

**Issue by vfunc** [BrikerMan/BMPlayer#140]
if let item = playerLayer?.playerItem {
            let option = self.audioTrackGroup?.options[index]
            item.select(option, in: self.audioTrackGroup!)
        }

**Comment by vfunc** [comment]
已解决。

**Comment by BrikerMan** [comment]
可以在初始化 `BMPlayerResource` 时候带上属性，参照自定义请求 header。
