### ISSUE TITLE
Support for multiple videos in a playlist? Like Instagram/Snapchat stories.

### ISSUE THREAD

**Issue by dannysood** [BrikerMan/BMPlayer#145]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.
- [x] I have searched in [existing issues](https://github.com/BrikerMan/BMPlayer/issues?utf8=%E2%9C%93&q=) but did not find the same one.

## Installed with 
- [ ] Carthage
- [x] Cocoapods

## Issue Description
I am trying to figure out how can I pass a list of urls instead of one to allow multiple videos to play as a playlist as I want to implement a feature similar to how snapchat/Instagram stories work. AVKit supports it using replaceCurrentItem.
### What

[Tell us about the issue]

### Reproduce
Not applicable.
[The steps to reproduce this issue. What is the URL you were trying to play, where did you put your code, etc.]

### Other Comment

[Add anything else here]

**Comment by BrikerMan** [comment]
Not yet, you will have to maintain the playlist by yourself.
