### ISSUE TITLE
Hide Status Bar only on Full Screen

### ISSUE THREAD

**Issue by gmogames** [BrikerMan/BMPlayer#147]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.
- [X] I have searched in [existing issues](https://github.com/BrikerMan/BMPlayer/issues?utf8=%E2%9C%93&q=) but did not find the same one.

## BMPlayer version 
0.8.7

## Installed with 
- [ ] Carthage
- [X] Cocoapods

### What

Is there any way to make the status bar only hide on fullscreen? Everytime the video is playing smaller in portrait mode, it hide it.

**Comment by kevin-zqw** [comment]
Hi there

I have the same issue, finally I managed to fix it by subclass BMPlayerControlView, just override controlViewAnimation method.

`    open func controlViewAnimation(isShow: Bool) {
        let alpha: CGFloat = isShow ? 1.0 : 0.0
        self.isMaskShowing = isShow
        
        // Remove this line
        // UIApplication.shared.setStatusBarHidden(!isShow, with: .fade)
        
        UIView.animate(withDuration: 0.3, animations: {
            self.topMaskView.alpha    = alpha
            self.bottomMaskView.alpha = alpha
            self.mainMaskView.backgroundColor = UIColor ( red: 0.0, green: 0.0, blue: 0.0, alpha: isShow ? 0.4 : 0.0)
            
            if isShow {
                if self.isFullscreen { self.chooseDefitionView.alpha = 1.0 }
            } else {
                self.replayButton.isHidden = true
                self.chooseDefitionView.snp.updateConstraints { (make) in
                    make.height.equalTo(35)
                }
                self.chooseDefitionView.alpha = 0.0
            }
            self.layoutIfNeeded()
        }) { (_) in
            if isShow {
                self.autoFadeOutControlViewWithAnimation()
            }
        }
    }`

**Comment by BrikerMan** [comment]
Change this with the `playerOrientChanged` delegate.
