### ISSUE TITLE
Swift升级支持

### ISSUE THREAD

**Issue by linbx08** [BrikerMan/BMPlayer#148]
hello, 请问你们这个项目有计划升级到Swift4.0的计划不

**Comment by BrikerMan** [comment]
嗯嗯，当然会升级~

**Comment by linbx08** [comment]
Ah Fantastic! 期待新版本早日降临

**Comment by linbx08** [comment]
hi,你好,请问Xcode9正式发布后 BMPlayer会正式发布Swift4.0版本库吗

**Comment by BrikerMan** [comment]
恩，会尽快跟进的。不会超过 1 周。

**Comment by BrikerMan** [comment]
已升级~， 正式版待 Xcode9 正式版发布在跟上。

**Comment by linbx08** [comment]
thank you very much

**Comment by linbx08** [comment]
哈喽, 这个项目集成了snpkit 官方的snapkit已经迁移到Swif4.0了 希望作者能跟进更新

**Comment by BrikerMan** [comment]
已更新 @linbx08

**Comment by BrikerMan** [comment]
Released v1.0.0 for swift4.
