### ISSUE TITLE
SIGTRAP问题

### ISSUE THREAD

**Issue by linbx08** [BrikerMan/BMPlayer#151]
hello, 在使用BMPlayer播放视频时候偶尔会上报SIGTRAP问题到buggly. 使用作者的demo打上全局断点ALL Exceptions 时候也会出现cxa throw.请问该如何解决

**Comment by BrikerMan** [comment]
我查查看吧... 这个我也不知道

**Comment by mokai** [comment]
在Xcode的Crashes中统计到一条数据，闪退在BMPlayer.formatSecondsToString第二行代码上。
```
let Sec = Int(secounds.truncatingRemainder(dividingBy: 60))
```

闪退的设备为iPad Air，iOS8.2，我试着用模拟器去复现，但并没有闪退。

**Comment by BrikerMan** [comment]
是不是 32 位系统的问题，你手上有 32 位设备的话可以试试。

**Comment by linbx08** [comment]
在iOS10 真机iPhone6上也会出现问题

**Comment by mokai** [comment]
应该是secounds为nan会出现这种情况，加个判断就行了

**Comment by BrikerMan** [comment]
欢迎提交 pull request

**Comment by mokai** [comment]
https://github.com/BrikerMan/BMPlayer/pull/160 已RP
