### ISSUE TITLE
keras中代码中有个问题

### ISSUE THREAD

**Issue by jiangchao123** [BrikerMan/BMPlayer#156]
## Check List

抱歉在你的博客上发现了个问题，但是没找到地方留言，所以只能暂时在这个地方留言了。
博客链接：https://eliyar.biz/using-pre-trained-gensim-word2vector-in-a-keras-model-and-visualizing/

在文章中的embedding层，代码是：
embedding_layer = Embedding(len(embeddings_matrix) + 1,
                            EMBEDDING_DIM,
                            weights=[embeddings_matrix]
                            trainable=False)
但是我觉得，第一个参数应该是len(embeddings_matrix)而不用再加一了。因为在上面embeddings_matrix定义的时候就已经加过一了。如下：
embeddings_matrix = np.zeros((len(model.wv.vocab.items()) + 1, model.vector_size))

不知道我理解的对不对，希望得到答复。另外博客里的第二个链接失效了。作者写的博客很赞，通俗易懂，感谢~

**Comment by BrikerMan** [comment]
你说的对呢~ 这个我看了一下项目中已经改了。 博客里面有错误，谢谢纠错~

**Comment by BrikerMan** [comment]
已更新博客~
