### ISSUE TITLE
carthage怎么还是报错，build不了。

### ISSUE THREAD

**Issue by HanXiaoTeng** [BrikerMan/BMPlayer#159]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.
- [x] I have searched in [existing issues](https://github.com/BrikerMan/BMPlayer/issues?utf8=%E2%9C%93&q=) but did not find the same one.

## Installed with 
- [x] Carthage
- [ ] Cocoapods

### What

[Tell us about the issue]

### Reproduce

[The steps to reproduce this issue. What is the URL you were trying to play, where did you put your code, etc.]

### Other Comment

[Add anything else here]

**Comment by HanXiaoTeng** [comment]
cathage依然报错。编译不了

**Comment by BrikerMan** [comment]
这个等等吧... Swift 版本迁移阶段... 问题比较多，等第三方库都跟上了我在解决。先用 cocoapods 吧

**Comment by BrikerMan** [comment]
已修复
