### ISSUE TITLE
Xcode 8 GM Seed // Swift 3 Compile errors

### ISSUE THREAD

**Issue by thetravischannel** [BrikerMan/BMPlayer#16]
Using the Swift 3 branch through cocoapods, withe the latest release (GM Seed) of Xcode 8, compilation of project results in the following errors:

![screen shot 2016-09-08 at 2 51 06 pm](https://cloud.githubusercontent.com/assets/17730193/18364466/fe033286-75d3-11e6-994c-bac6e59b7be0.png)

**Comment by BrikerMan** [comment]
BMPlayer has depend on [Snapkit](https://github.com/mattsrobot/SnapKit) and [NVActivityIndicatorView](https://github.com/ninjaprox/NVActivityIndicatorView/). I have to wait until those two fully support Swift3.

**Comment by thetravischannel** [comment]
Thanks for the quick reply, I am testing with the Swift 3 branches of SnapKit, and a fork of NVActivityIndicatorView. I appreciate your work, and will check back when those projects become more compatible with Swift 3.

**Comment by BrikerMan** [comment]
@thetravischannel completed swift3 support.
