### ISSUE TITLE
Carthage won't compile

### ISSUE THREAD

**Issue by Lufthummel** [BrikerMan/BMPlayer#164]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.
- [ ] I have searched in [existing issues](https://github.com/BrikerMan/BMPlayer/issues?utf8=%E2%9C%93&q=) but did not find the same one.

## Installed with 
- [ x] Carthage
- [ ] Cocoapods

## Issue Description
Compile error due to missing file
### What

error: no such file or directory: '/Users/hkremmin/dev/BMPlayer/Example/Carthage/Checkouts/BMPlayer/Source/BMPlayerManager.swift'

[Tell us about the issue]

### Reproduce

[The steps to reproduce this issue. What is the URL you were trying to play, where did you put your code, etc.]

### Other Comment

[Add anything else here]

**Comment by BrikerMan** [comment]
Please try the latest version.
