### ISSUE TITLE
视频播放完毕重播的BUG

### ISSUE THREAD

**Issue by tooodooo** [BrikerMan/BMPlayer#17]
视频播完后会出现重播按钮，不通过重播按钮来重播的步骤：

1.按空白处隐藏重播按钮
2.再次点击出现控制条，此时重播按钮已消失
3.点击下方三角播放按钮无法播放
4.拖动进度条可以进行播放，播放按钮的状态不正确，有时状态进度条的进度也不正确

**Comment by BrikerMan** [comment]
那就是出现重播按钮的时候disable tapGesture来避免这个问题咯

**Comment by tooodooo** [comment]
简单的禁用启用会带来顶部的导航条也无法显示了，只有点按了重播再启用，体验不好

**Comment by BrikerMan** [comment]
也对，我想想方案，下一版本更新~

**Comment by BrikerMan** [comment]
@tooodooo 尝试解决了，试试。记得反馈。

**Comment by BrikerMan** [comment]
@tooodooo 麻烦给个反馈
