### ISSUE TITLE
Hide full screen button

### ISSUE THREAD

**Issue by GaneshManickam** [BrikerMan/BMPlayer#175]
How to hide full screen button?

**Comment by MangoMade** [comment]
create a subclass of BMPlayerCustomControlView
override 'func customizeUIComponents()' methed.
in the customizeUIComponents methed, set fullscreenButton.isHidden = true

```
class PlayerControlView: BMPlayerCustomControlView {
    override func customizeUIComponents() {
        super.customizeUIComponents()
        fullscreenButton.isHidden = true
    }
}

```

then, in your ViewController :

```
let player = BMPlayer(customControlView: PlayerControlView())
```

**Comment by BrikerMan** [comment]
@MangoMade thanks.
