### ISSUE TITLE
Buffer size find in player

### ISSUE THREAD

**Issue by suraj-ios** [BrikerMan/BMPlayer#176]
@BrikerMan ,

Could you please help me how to find Buffer size?. 

Thanks in advance.

**Comment by BrikerMan** [comment]
check these urls, you could access to BMPlayes' AVPlayer instance.
- [Buffer size for AVPlayer / AVPlayerItem](https://stackoverflow.com/questions/21400591/buffer-size-for-avplayer-avplayeritem)
- [set AVPlayer AVPlayerItem buffer size?](https://stackoverflow.com/questions/43720129/set-avplayer-avplayeritem-buffer-size)
