### ISSUE TITLE
如何播放本地视频

### ISSUE THREAD

**Issue by tangjiarao** [BrikerMan/BMPlayer#188]
URL:
file:///Users/tangjiarao/Library/Developer/CoreSimulator/Devices/D59DA47E-7D37-48B8-9B59-40C407ACD8DB/data/Containers/Data/Application/E5DD084C-19A6-4E3E-8EE0-A2151FD7407D/Documents/OnlineLearnPDF/ff8080815b0e7c36015b0e7d07060000/dba6e8d3-c5f1-40b6-86e1-46898224005a.mp4

播放:
let asset = BMPlayerResource(url: url!, name: itemTuple?.chapter.title ?? "视频")

但是无法播放

**Comment by lwt001no1** [comment]
i think u could try ****build phases-copy bundle resourse-add your movie

**Comment by tangjiarao** [comment]
I don't understand, can you make it clear?

**Comment by Bhavin-Pavans** [comment]
@tangjiarao  I've tried this code  and it works for me 
let asset = BMPlayerResource(url: URL(fileURLWithPath: localURL),name: "") player.setVideo(resource: asset)

**Comment by BrikerMan** [comment]
Please check your local file url.
