### ISSUE TITLE
I could not import BMPlayer

### ISSUE THREAD

**Issue by lwt001no1** [BrikerMan/BMPlayer#189]
this is my podfile ：
source 'https://github.com/CocoaPods/Specs.git'
 platform :ios, '8.0'

target 'testbmplayer’ do
use_frameworks!

pod 'BMPlayer', '~> 1.0.0'

  # Pods for PlayerDemo

end
--------------------------------------------------
but it always error"Cannot load underlying module for 'BMPlayer'",after pod install.
i think my setting error ?i am a new man in swift,thanks

**Comment by BrikerMan** [comment]
Try this
```
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BMPlayer_Example' do
  pod 'BMPlayer'
end
```
