### ISSUE TITLE
建议增加播放状态监听回调

### ISSUE THREAD

**Issue by 6ag** [BrikerMan/BMPlayer#19]
就是类似于要做连续播放的话，在播放结束的时候能给个回调，或者播放正常结束，还是用户手动结束，还是其他状态啥的。

**Comment by BrikerMan** [comment]
恩，现在是开放了 `BMPlayerLayer` 来允许自定义，可以在 `BMPlayer` 层也加一些回掉。等我有空就加上。

**Comment by 6ag** [comment]
好的，谢谢
还有一个问题，我在viewDidApear里调用autoplay的话播放按钮状态会经常没有切换，就是视频在播放了，但显示的还是播放状态的图标而不是暂停

**Comment by BrikerMan** [comment]
Fixed at https://github.com/BrikerMan/BMPlayer/commit/cf92d64ffbfe98f5f3303857f1b824d4fd5b67c3 && https://github.com/BrikerMan/BMPlayer/commit/dcafc08f559dc832a29af33a2bdc4acb216f3263
