### ISSUE TITLE
Add custom button 

### ISSUE THREAD

**Issue by Momeks** [BrikerMan/BMPlayer#193]
I was wondering how can i add custom button to the player  with custom icon  ?

**Comment by BrikerMan** [comment]
You can, Check the demo.

**Comment by Momeks** [comment]
Thanks but button appears only in landscape mode , is there any limitation ? or I can add it both landscape and portrait ?

**Comment by BrikerMan** [comment]
Yes, you can.

**Comment by Momeks** [comment]
Would you please help me more ? how should I exactly add button in both landscape and portrait ? The demo is not clear
