### ISSUE TITLE
Hide rectangle button in fullscreen

### ISSUE THREAD

**Issue by Momeks** [BrikerMan/BMPlayer#196]
I am using custom BMPlayer with storyboard , I have a problem with a blank rectangle in full screen: 
https://i.stack.imgur.com/v8MBg.png

How can I remove it ?

**Comment by BrikerMan** [comment]
Are you setting assets with code like this?
```
let asset = BMPlayerResource(url: URL(string: "http://baobab.wdjcdn.com/14525705791193.mp4")!,
                             name: "Title here")
player.setVideo(resource: asset)
```

**Comment by Momeks** [comment]
Thanks for your reply , no just URL :

      self.asset = BMPlayerResource(url: URL(string: self.urlArray.last!)!)
                self.player.setVideo(resource: self.asset)

**Comment by Momeks** [comment]
any solution ?!

**Comment by Momeks** [comment]
I fix it by adding 

```
   func setupUIComponents() {
chooseDefitionView.alpha = 0
}
```
in `BMPlayerControlView.swift`
