### ISSUE TITLE
pod 

### ISSUE THREAD

**Issue by Erickson0806** [BrikerMan/BMPlayer#2]
pod search BMPlayer
[!] Unable to find a pod with name matching `BMPlayer'

**Comment by Recursion0210** [comment]
Do you pod update ?

在 2016年5月23日，下午6:26，chao <notifications@github.com<mailto:notifications@github.com>> 写道：


pod search BMPlayer
[!] Unable to find a pod with name matching `BMPlayer'

**Comment by BrikerMan** [comment]
@Erickson0806 please run `pod repo update` first.
