### ISSUE TITLE
iOS10里缓冲结束后菊花还是一直转

### ISSUE THREAD

**Issue by 6ag** [BrikerMan/BMPlayer#20]
缓冲结束后白色菊花没有隐藏哦

**Comment by 6ag** [comment]
可播放后，没有回调 `.BufferFinished` 状态，我临时修改了下，大神求修复

**Comment by BrikerMan** [comment]
这两天修复一下~

**Comment by 6ag** [comment]
大神，bug还在啊。
```swift
case "playbackLikelyToKeepUp":
                    if item.playbackBufferEmpty {
                        if state != .BufferFinished {
                            self.state = .BufferFinished
                        }
                    }
```

**Comment by BrikerMan** [comment]
最近太忙了还没来得及改啊。你改完发 pull request 呗。给你合并。

六阿哥 <notifications@github.com>于2016年9月26日周一 上午9:34写道：

**Comment by jihongboo** [comment]
今天更新了一下，bug还是没有修好。。。回调倒是走了，不过不知道为什么readyToPlay里面没有隐藏loading的方法，我自行添加了一下。
在代理BMPlayerLayerViewDelegate中的方法
func bmPlayer(player: BMPlayerLayerView, playerStateDidChange state: BMPlayerState)
中的case BMPlayerState.readyToPlay:中加了一个controlView.hideLoader()方法就OK了。希望作者尽快更新一下，谢谢～

**Comment by jihongboo** [comment]
虽然菊花的问题暂时解决了，但控制面板的隐藏和播放按钮的样式还需要依据player.isPlaying的属性，不过这个属性貌似也不管用了，没办法我只能暂时把autoFadeOutControlBar()拿到判断外面来。。。

**Comment by BrikerMan** [comment]
@jihongboo 你说的 `控制面板的隐藏和播放按钮的样式还需要依据player.isPlaying的属性` 没太明白，详细说一下吧。我今天改掉。

**Comment by BrikerMan** [comment]
已修复
