### ISSUE TITLE
can't play youtube videos..

### ISSUE THREAD

**Issue by jatinverma007** [BrikerMan/BMPlayer#205]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.
- [ ] I have searched in [existing issues](https://github.com/BrikerMan/BMPlayer/issues?utf8=%E2%9C%93&q=) but did not find the same one.

## Installed with 
- [ ] Carthage
- [ ] Cocoapods

### What

[Tell us about the issue]

### Reproduce

[The steps to reproduce this issue. What is the URL you were trying to play, where did you put your code, etc.]

### Other Comment

[Add anything else here]

**Comment by Mik-chan** [comment]
I'm not author of this program, but, as I see in sources, you can play any video file which AVPlayer supports. For remote videos you need an URL with _file_. And as you can't get _file's url_ from youtube, playing youtube videos is impossible or at least is not simple action.

**Comment by BrikerMan** [comment]
@Mik-chan is correct, thanks.
