### ISSUE TITLE
会出swift2.3版本不？

### ISSUE THREAD

**Issue by tooodooo** [BrikerMan/BMPlayer#21]
XCODE被升级，只能2.3和3.0选一了，3.0暂时不能升，求swift2.3版本，哈哈

**Comment by BrikerMan** [comment]
尽量一次性到3.0，因为我这里还有俩依赖的swift库，搞起来略麻烦。

**Comment by tooodooo** [comment]
我用了Alamofire，swift3.0版本最低只支持iOS9，唉，这次升级搞的好麻烦，还不如之前直接用OC的库，升级倒是安全

**Comment by BrikerMan** [comment]
@tooodooo 老外有些太任性，Alamofire 我直接替换掉了，换成了 Pitaya ，很赞的封装。还有一个库也给我写支持版本 8.0。然后自己 fork 下来改了一下语法。用的好好的~

**Comment by tooodooo** [comment]
研究一下你说的Pitaya，我也考虑把Alamofire换掉了
