### ISSUE TITLE
Override action of topBar.

### ISSUE THREAD

**Issue by adrianodiasx93** [BrikerMan/BMPlayer#22]
Swift 2.2 - release v0.3.3

In full screen mode, when I tap the topbar, I'd like to return to the root controller instead of going to portrait mode. 

I know if I set `self.navigationController?.popToRootViewControllerAnimated(true)`, I will be sent to the root view when I tap the navigation Back button. I wonder if there's something similar to the topbar.

Or maybe should I override or rewrite some method? Suggestions?

Thanks in advance!

**Comment by adrianodiasx93** [comment]
`@objc private func backButtonPressed(button: UIButton) {
        if isFullScreen {
            fullScreenButtonPressed(nil)
        } else {
            playerLayer?.prepareToDeinit()
            backBlock?()
        }
    }`

I guess if some of these methods were public (open in swift 3.0) I could do some customization.

**Comment by BrikerMan** [comment]
Yes, it will do the job. I will do this adjustment this weekend~ Thanks for your advice.

**Comment by BrikerMan** [comment]
Is there any further question here?
