### ISSUE TITLE
播放器速度设置

### ISSUE THREAD

**Issue by jufengliushao** [BrikerMan/BMPlayer#231]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.
- [ ] I have searched in [existing issues](https://github.com/BrikerMan/BMPlayer/issues?utf8=%E2%9C%93&q=) but did not find the same one.

## BMPlayer version 
1.0.0

## Installed with 
- [ ] Cocoapods

## Issue Description
1.未找到对应的播放速度设置接口
2.设置对应的avplayer rate  不起作用

### What
针对上面的第二条，是我设置作用，还是需要自行修改源码？

[Tell us about the issue]

### Reproduce

[The steps to reproduce this issue. What is the URL you were trying to play, where did you put your code, etc.]

### Other Comment

[Add anything else here]

**Comment by birdmichael** [comment]
理论上可以拿到播放器然后自行设置

**Comment by ChinaKeep** [comment]
完全无效，不知道框架哪里有问题
