### ISSUE TITLE
自动播放的时候，先隐藏了statusBar，没有同步隐藏playerController。

### ISSUE THREAD

**Issue by AlanMoMo** [BrikerMan/BMPlayer#244]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.
- [x] I have searched in [existing issues](https://github.com/BrikerMan/BMPlayer/issues?utf8=%E2%9C%93&q=) but did not find the same one.

## Installed with 

- [x] Cocoapods

### What

[Tell us about the issue]
导致此时返回其他页面，会把其他页面的statusBar隐藏了。
建议开放接口，有些时候在非全屏页面播放时，不需要影藏statusBar。

### Reproduce

[The steps to reproduce this issue. What is the URL you were trying to play, where did you put your code, etc.]

### Other Comment

[Add anything else here]

**Comment by birdmichael** [comment]
可以重写。再次设置状态栏
