### ISSUE TITLE
播放本地文件时，如果是缓存分支，会出现无法播放，原因是VIMediaCache扩展的获取asset在文件路径前拼接了他的标识。有时间修复一下吧！

### ISSUE THREAD

**Issue by tang4595** [BrikerMan/BMPlayer#246]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.
- [ ] I have searched in [existing issues](https://github.com/BrikerMan/BMPlayer/issues?utf8=%E2%9C%93&q=) but did not find the same one.

## Installed with 
- [ ] Carthage
- [ ] Cocoapods

### What

[Tell us about the issue]

### Reproduce

[The steps to reproduce this issue. What is the URL you were trying to play, where did you put your code, etc.]

### Other Comment

[Add anything else here]

**Comment by ssyzh** [comment]
更新最新的VIMediaCache就好了，这不是不是BMPlayer的问题

**Comment by BrikerMan** [comment]
> 更新最新的VIMediaCache就好了，这不是不是BMPlayer的问题

谢谢，我尽快更新一下版本号~
