### ISSUE TITLE
swift 4.2 version can not work, please check your  podspec about  NVActivityIndicatorView

### ISSUE THREAD

**Issue by QiaoBangZhu** [BrikerMan/BMPlayer#247]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.
- [ ] I have searched in [existing issues](https://github.com/BrikerMan/BMPlayer/issues?utf8=%E2%9C%93&q=) but did not find the same one.

## Installed with 
- [ ] Carthage
- [ ] Cocoapods

### What

[Tell us about the issue]

### Reproduce

[The steps to reproduce this issue. What is the URL you were trying to play, where did you put your code, etc.]

### Other Comment

[Add anything else here]

**Comment by darren1192** [comment]
I have the same problem。

**Comment by benbahrenburg** [comment]
PR submitted that fixes that issue #251

**Comment by sourabh-verma-mt** [comment]
PR submitted but no official new release yet. Could it be made official with new version so our code stays clean ?

**Comment by BrikerMan** [comment]
Please update to the version 1.2.0, sorry for the delay.
