### ISSUE TITLE
播放时，中间的 loadingIndector 一直处于显示状态

### ISSUE THREAD

**Issue by klaus01** [BrikerMan/BMPlayer#25]
使用 `Example` 播放 `http://200038134.vod.myqcloud.com/200038134_854a16ed51dd37be0ea633ba4d2f3516199e2950.f210.av.m3u8` 重现问题。

**Comment by klaus01** [comment]
试了 `ZFPlayer` 没这问题。

**Comment by BrikerMan** [comment]
已解决~

**Comment by h81061678** [comment]
你好，我使用cocoapods 進行了update 版本是0.3.3但運行時，影片已開始播放，但loading並未隱藏。

**Comment by BrikerMan** [comment]
@h81061678 
```
pod 'BMPlayer', :git => 'https://github.com/BrikerMan/BMPlayer.git'
```
来安装
