### ISSUE TITLE
BMPlayer CacheSupport not loading local video url

### ISSUE THREAD

**Issue by socquique** [BrikerMan/BMPlayer#252]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.
- [x] I have searched in [existing issues](https://github.com/BrikerMan/BMPlayer/issues?utf8=%E2%9C%93&q=) but did not find the same one.

## BMPlayer version 
BMPlayer/CacheSupport 1.0.2

## Installed with 
- [ ] Carthage
- [x] Cocoapods

## Issue Description
Local video saved in documents folder not working.

### What
I'm using the cache version of the repository (pod 'BMPlayer/CacheSupport', :git => 'https://github.com/BrikerMan/BMPlayer.git').

Stream videos works fine, but local downloaded mp4 videos always fail.

### Reproduce
I'm trying to reproduce a file with format "file:///var/mobile/Containers/Data/Application/3FF735ED-A994-482C-A598-8ABD18FBDC98/Documents/1757106.mp4", but always reports state - error

**Comment by socquique** [comment]
Solved by my own just changing this:

...
     fileprivate func configPlayer(){
         player?.removeObserver(self, forKeyPath: "rate")
         playerItem = AVPlayerItem(asset: urlAsset!)

        if (urlAsset?.url.absoluteString.contains("file://") ?? false){
            playerItem = AVPlayerItem(url: URL(string:urlAsset!.url.absoluteString.replacingOccurrences(of: "__VIMediaCache___:", with: ""))!)
        }
       
        player = AVPlayer(playerItem: playerItem)
...

**Comment by birdmichael** [comment]
#296
