### ISSUE TITLE
Swift4.2更新支持

### ISSUE THREAD

**Issue by linbx08** [BrikerMan/BMPlayer#253]
楼主你好. 请问这个项目有计划升级到Swift4.2吗?

**Comment by ceeyang** [comment]
fork 了作者的源码, 并试着改了下, 然后成功了.

**Comment by linbx08** [comment]
@ceeyang  厉害.

**Comment by BrikerMan** [comment]
@ceeyang 一直忙疏忽更新了，等年后直接更新 swift 5.0 和 swift 4.2 版本吧。如果可以，麻烦一起做一下适配，谢谢啦。

**Comment by BrikerMan** [comment]
发布了 1.2.0 版本，谢谢支持。
