### ISSUE TITLE
This player not supporting .m3u8 files

### ISSUE THREAD

**Issue by SureshValle480** [BrikerMan/BMPlayer#259]
This player not supporting .m3u8 file app geting crash.

**Comment by BrikerMan** [comment]
Please provide the demo m3u8 file to reproduce the crash.

**Comment by m3u8playlist** [comment]
2019-02-16 16:28:57.099156+0800 BMPlayer_Example[54261:468715] Task <C766F1BD-E2E6-467A-B4BF-A1CF28F1835B>.<1> load failed with error Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://nhkworld.webcdn.stream.ne.jp/www11/nhkworld-tv/global/263941/live_wa_s.m3u8, NSErrorFailingURLKey=https://nhkworld.webcdn.stream.ne.jp/www11/nhkworld-tv/global/263941/live_wa_s.m3u8, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <C766F1BD-E2E6-467A-B4BF-A1CF28F1835B>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <C766F1BD-E2E6-467A-B4BF-A1CF28F1835B>.<1>, NSLocalizedDescription=cancelled} [-999]

**Comment by m3u8playlist** [comment]
> 2019-02-16 16:28:57.099156+0800 BMPlayer_Example[54261:468715] Task .<1> load failed with error Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://nhkworld.webcdn.stream.ne.jp/www11/nhkworld-tv/global/263941/live_wa_s.m3u8, NSErrorFailingURLKey=https://nhkworld.webcdn.stream.ne.jp/www11/nhkworld-tv/global/263941/live_wa_s.m3u8, _NSURLErrorRelatedURLSessionTaskErrorKey=(
> "LocalDataTask .<1>"
> ), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask .<1>, NSLocalizedDescription=cancelled} [-999]

the m3u8 link works fine with safari or avkit, but it can not be played with  BMPlayer

**Comment by weitieda** [comment]
This is a test `m3u8` file from `Apple`, seems like not able to play...

`https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_adv_example_hevc/master.m3u8`

**Comment by m3u8playlist** [comment]
It 

> > 2019-02-16 16:28:57.099156+0800 BMPlayer_Example[54261:468715] Task .<1> load failed with error Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://nhkworld.webcdn.stream.ne.jp/www11/nhkworld-tv/global/263941/live_wa_s.m3u8, NSErrorFailingURLKey=https://nhkworld.webcdn.stream.ne.jp/www11/nhkworld-tv/global/263941/live_wa_s.m3u8, _NSURLErrorRelatedURLSessionTaskErrorKey=(
> > "LocalDataTask .<1>"
> > ), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask .<1>, NSLocalizedDescription=cancelled} [-999]
> 
> the m3u8 link works fine with safari or avkit, but it can not be played with BMPlayer

the same situation.

**Comment by frozenthrone** [comment]
> This is a test `m3u8` file from `Apple`, seems like not able to play...
> 
> `https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_adv_example_hevc/master.m3u8`

the example does not work, But in my personal project, it works fine.

**Comment by sk-in** [comment]
same problem
