### ISSUE TITLE
swift 5.0 集成报错

### ISSUE THREAD

**Issue by wty302857194** [BrikerMan/BMPlayer#266]
<img width="296" alt="image" src="https://user-images.githubusercontent.com/12996539/55391701-75a3aa80-556c-11e9-813c-86486f51c8f0.png">

**Comment by BrikerMan** [comment]
请提供更加完整的信息，我这里没有能够复现。

**Comment by wty302857194** [comment]
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/12996539/55398204-8d822b00-557a-11e9-964a-906f99940130.png">

**Comment by birdmichael** [comment]
'BMPlayer', '~> 1.3.0' 未能复现，如果还是存在麻烦重新打开
