### ISSUE TITLE
turn off volume

### ISSUE THREAD

**Issue by uknowmeright** [BrikerMan/BMPlayer#27]
So I want to initially begin autoplaying the video with volume set to 0.
How do I do this?

I have been using self.videoView..reduceVolume()
but that mutes the entire phone. I want the initial volume of ONLY the video to be 0. Then when the video is tapped to bring it up to say 50%. 

Is this possible?

Thanks in advance

**Comment by BrikerMan** [comment]
I suggest to fork BMPlayer and make same change in https://github.com/BrikerMan/BMPlayer/blob/master/BMPlayer/Classes/BMPlayerLayerView.swift#L49 
```
lazy var player: AVPlayer? = {
    if let item = self.playerItem {
        let player = AVPlayer(playerItem: item)
        player.isMuted = true
        return
    }
    return nil
}()
```

And add change volume to 50% at https://github.com/BrikerMan/BMPlayer/blob/master/BMPlayer/Classes/BMPlayer.swift
