### ISSUE TITLE
无法播放不带视频格式的在线视频

### ISSUE THREAD

**Issue by xiaomage1478** [BrikerMan/BMPlayer#271]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.
- [ ] I have searched in [existing issues](https://github.com/BrikerMan/BMPlayer/issues?utf8=%E2%9C%93&q=) but did not find the same one.

## Installed with 
- [ ] Carthage
- [x] Cocoapods

## Issue Description

比如：https://v.qq.com/iframe/player.html?vid=g0528hi619c 这种格式的视频链接无法播放

[Tell us about the issue]

### Reproduce

[The steps to reproduce this issue. What is the URL you were trying to play, where did you put your code, etc.]

### Other Comment

[Add anything else here]

**Comment by xiaomage1478** [comment]
https://v.qq.com/iframe/player.html?vid=g0528hi619c,请问这种格式的链接无法播放,该怎么处理

**Comment by BrikerMan** [comment]
因为这个是一个网页链接，不是一个视频真实地址。这个才是上面视频的真实地址，你需要解析出来才能播放：
```
http://ugcydzd.qq.com/uwMROfz2r5zCIaQXGdGnC2dfhzk_jigLCkkLvI0zErHWpl3G/g0528hi619c.m701.mp4?vkey=3F90BA2CC80BE9A31619D2684E37DF12F39F3C43D7A5D24882CB84731CF5B162CAD5EE014FFF58C4277DC07481903953150220F5F43FB6A3899A95AB6B14E3CDFA3810A73C87CDA6B24A690CDA950FDAF180FB60496A02EE55BF203BD784B87F1C4D07AFB2B66414A17FBB083722A6EDCABB747EBC23BCAD785A6DDB3ADD9911&br=28&platform=2&fmt=auto&level=0&sdtfrom=v1010&guid=0cb213eab3b75aea1b2d9de4444a87e0
```

**Comment by xiaomage1478** [comment]
> 因为这个是一个网页链接，不是一个视频真实地址。这个才是上面视频的真实地址，你需要解析出来才能播放：
> 
> ```
> http://ugcydzd.qq.com/uwMROfz2r5zCIaQXGdGnC2dfhzk_jigLCkkLvI0zErHWpl3G/g0528hi619c.m701.mp4?vkey=3F90BA2CC80BE9A31619D2684E37DF12F39F3C43D7A5D24882CB84731CF5B162CAD5EE014FFF58C4277DC07481903953150220F5F43FB6A3899A95AB6B14E3CDFA3810A73C87CDA6B24A690CDA950FDAF180FB60496A02EE55BF203BD784B87F1C4D07AFB2B66414A17FBB083722A6EDCABB747EBC23BCAD785A6DDB3ADD9911&br=28&platform=2&fmt=auto&level=0&sdtfrom=v1010&guid=0cb213eab3b75aea1b2d9de4444a87e0
> ```

https://www.youjiaodaxue.cn//home_educations/2/video/?appid=easyteaching_app&token=119_9417bc9e3d254c52b0dd22b84c03d199
这个视频链接也不行

**Comment by BrikerMan** [comment]
下面的这个需要排查一下，可能确实是问题。

**Comment by xiaomage1478** [comment]
> 下面的这个需要排查一下，可能确实是问题。

嗯,拜托🙏了

**Comment by xiaomage1478** [comment]
> 下面的这个需要排查一下，可能确实是问题。

大神,这个问题有结论么,近期可有修复的可能性

**Comment by xiaomage1478** [comment]
是服务器的问题,没有支持断点续传.苹果是先发2个字节判断是否支持完整的断点续传,不支持就无法播放了.大神费心了
