### ISSUE TITLE
local downloaded video not playing

### ISSUE THREAD

**Issue by umairgillani94** [BrikerMan/BMPlayer#280]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.
-  I have searched in [existing issues](https://github.com/BrikerMan/BMPlayer/issues?utf8=%E2%9C%93&q=) but did not find the same one.

## Installed with 
- Carthage
-  Cocoapods

## Issue Description
I am trying to play a video downloaded at my local path but the player always shows loading nothing else.

### Reproduce

URL Is : file:///Users/umairgillani/Library/Developer/CoreSimulator/Devices/88E881B4-A97A-4A15-9EF1-E4859C774683/data/Containers/Data/Application/F2ADD14C-50A3-48C2-BEE3-10B37B8B59B2/Documents/VBOX/144_Main_Khayal_Hoon_Kisi_Aur_Ka_-_Episode_1_9156.3gp

**Comment by aadeshmindtickle** [comment]
Facing same issue; any work around?

**Comment by umairgillani94** [comment]
> Facing same issue; any work around?

no @aadeshmindtickle , i played it using AVPlayer manually.
