### ISSUE TITLE
v1.3.0 minimum requires iOS 10.0

### ISSUE THREAD

**Issue by JinJieGu** [BrikerMan/BMPlayer#282]
Thanks for your great library! I want support ios 9.0 but v1.3.0 change the min deployment target to 10.0

**Comment by danmingyang** [comment]
me too

**Comment by birdmichael** [comment]
@JinJieGu @danmingyang 

Because we are dependent `SnapKit`
SnapKit Requirements:
iOS 10.0+ / Mac OS X 10.12+ / tvOS 10.0+
Xcode 10.0+
Swift 4.0+

Sorry not available on iOS 9.0
