### ISSUE TITLE
How to disable full screen?

### ISSUE THREAD

**Issue by Elamuruga** [BrikerMan/BMPlayer#289]
I don't want to show a video in full screen how to disable that, Could you please help me with this?

**Comment by birdmichael** [comment]
@Elamuruga 
hi~
you can do this:
```
let controller = BMPlayerControlView()
player = BMPlayer(customControllView: controller)
controller.fullscreenButton.isHidden = true
```

**Comment by Elamuruga** [comment]
@birdmichael Thank you so much really for your guidance it's working fine. I have one more doubt, Bottom toolbar like a play button, progress view, timing, and full-screen button was hide at some time I don't want to hide that it should be visible always. How can I achieve this? Could you please help with this? Thanks in advance

**Comment by birdmichael** [comment]
@Elamuruga 
fist make your PlayerControlView,and `override` the  `controlViewAnimation` func

```
class MyPlayerControlView: BMPlayerControlView {
    override func controlViewAnimation(isShow: Bool) {
        let alpha: CGFloat = isShow ? 1.0 : 0.0
        self.isMaskShowing = isShow

        UIApplication.shared.setStatusBarHidden(!isShow, with: .fade)

        UIView.animate(withDuration: 0.3, animations: {
            self.topMaskView.alpha    = alpha
            self.bottomMaskView.alpha = 1.0 // change to 1.0 
            self.mainMaskView.backgroundColor = UIColor(white: 0, alpha: isShow ? 0.4 : 0.0)

            if isShow {
                if self.isFullscreen { self.chooseDefinitionView.alpha = 1.0 }
            } else {
                self.replayButton.isHidden = true
                self.chooseDefinitionView.snp.updateConstraints { (make) in
                    make.height.equalTo(35)
                }
                self.chooseDefinitionView.alpha = 0.0
            }
            self.layoutIfNeeded()
        }) { (_) in
            if isShow {
                self.autoFadeOutControlViewWithAnimation()
            }
        }
    }
}
```
Because of the animation inside, you'd better not call `super`
then 
```
let controller = MyPlayerControlView()
player = BMPlayer(customControllView: controller)
```

**Comment by Elamuruga** [comment]
@birdmichael Thanks for your response friend but still bottom tools view was is hiding.

**Comment by birdmichael** [comment]
@Elamuruga 
Impossible. I've tested it.

change `self.bottomMaskView.alpha` always  `= 1.0`.

no more any code change the `bottomMaskView` alpha or isHide

**Comment by birdmichael** [comment]
@Elamuruga
If it's solved, please close it.

**Comment by Elamuruga** [comment]
@birdmichael Thanks friend for your kind and immediate responses. And sorry to bother you again is it possible to control orientation change? However, the device has rotated the player view should be in Portrait only... I want some requirements like that is possible?

**Comment by birdmichael** [comment]
@Elamuruga 
I don't support it at the moment, but I'll try to solve it in the near future

**Comment by Elamuruga** [comment]
@birdmichael ok waiting for that feature. Thank you for all your kind responses friend... Have a nice day

**Comment by jonfabris** [comment]
let controller = BMPlayerControlView()
        let player = BMPlayer(customControllView: controller)
        controller.backButton.isHidden = true
