### ISSUE TITLE
无法定制UI

### ISSUE THREAD

**Issue by yuzhi123** [BrikerMan/BMPlayer#291]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.
- [ ] I have searched in [existing issues](https://github.com/BrikerMan/BMPlayer/issues?utf8=%E2%9C%93&q=) but did not find the same one.

## Installed with 
- [ ] Carthage
- [ ] Cocoapods

### What

[Tell us about the issue]

### Reproduce

[The steps to reproduce this issue. What is the URL you were trying to play, where did you put your code, etc.]

### Other Comment

[Add anything else here]

**Comment by yuzhi123** [comment]
播放UI无法修改

**Comment by birdmichael** [comment]
please show me any code

**Comment by yuzhi123** [comment]
我想去掉播放器上的返还按钮，滑动条，全屏等按钮，但是找不到对应的api

**Comment by birdmichael** [comment]
比如：
```
let controller = BMPlayerControlView()
        player = BMPlayer(customControllView: controller)
        //隐藏全屏按钮并设置宽度20为右边宽度
        controller.fullscreenButton.isHidden = true
        controller.replayButton.isHidden = true
        controller.fullscreenButton.snp.updateConstraints { (make) in
            make.width.equalTo(20)
        }
```

**Comment by birdmichael** [comment]
如果解决了，麻烦关闭一下
