### ISSUE TITLE
我司的链接无法播放，麻烦作者帮忙看一下

### ISSUE THREAD

**Issue by MrWilsonXu** [BrikerMan/BMPlayer#293]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.
- [x] I have searched in [existing issues](https://github.com/BrikerMan/BMPlayer/issues?utf8=%E2%9C%93&q=) but did not find the same one.

## Installed with 
- [ ] Carthage
- [x] Cocoapods

### What

[Tell us about the issue]

### Reproduce

[The steps to reproduce this issue. What is the URL you were trying to play, where did you put your code, etc.]

### Other Comment

[Add anything else here]
视频连接：http://121.15.180.105/s/L2x1NzVfMDBfY21iZ29sZC4xMC8zM2U0ZjExZi1lYmViLTQ3MjktOTE3Yy03ZGFmMmQ4YjUyZTA_QVdTQWNjZXNzS2V5SWQ9bHU3NV91c2VyNiZFeHBpcmVzPTE2MDI5MDE5MzAmU2lnbmF0dXJlPWVwYU9sQXVCSTVBcjc1d0pRSnNFUEpjdzR1USUzRA==/Ipw4jgnNjIJMPwP9ajFhfNAv2xU=/lu75_user6/0

**Comment by birdmichael** [comment]
连接问题。。最简单的测试方法，通过Safari打开网页~
麻烦关闭一下

**Comment by birdmichael** [comment]
Safari也无法打开播放
