### ISSUE TITLE
Can I able to add custom Xib for player to customize ui?

### ISSUE THREAD

**Issue by kushalhyperlink** [BrikerMan/BMPlayer#298]
Hello Team, 

I've working with BMPlyaer since coule of days. I wanted to customuze complete UI. attached image. 
Can I able to add my cutomize xib to the player? or is there any other way? 

Please share your valuable feedback. 
![example](https://user-images.githubusercontent.com/56387038/71869732-2745bc80-3139-11ea-97ee-84656c4e9b5e.png)

**Comment by birdmichael** [comment]
@kushalhyperlink 
hello.
you can see `BMPlayerControlView`，base `BMPlayerControlView`。
you can change anything ,like `mainMaskView`,`topMaskView`,`bottomMaskView`,`playButton`...
then, you have to set the Target

**Comment by kushalhyperlink** [comment]
Hello @birdmichael 

Thank you for your prompt update, that means I can able to achieve mention UI with BMPlayer using snap kit. Am I correct?

**Comment by birdmichael** [comment]
@kushalhyperlink 
sure.
You can do anything in subclasses
