### ISSUE TITLE
iPhone5s View have a bug

### ISSUE THREAD

**Issue by dowhilenet** [BrikerMan/BMPlayer#3]
![qq20160526-0](https://cloud.githubusercontent.com/assets/10379476/15568524/f36fb4f6-235e-11e6-84c0-5add7e07ea81.png)

``` swift
        player.snp_makeConstraints { (make) in
            make.trailing.leading.equalTo(self.view)
            make.top.equalTo(self.view)
            make.height.equalTo(self.view.snp_width).multipliedBy(9.0 / 16.0).priority(750)
        }
```
iPhone5s 上横屏的时候并没有满屏，在iPhone6 or iPhone6P 没有这个问题

**Comment by dowhilenet** [comment]
只有我有这个问题吗？真机测试了一下，也是有问题的。约束感觉没有什么问题。就是在iPhone SE ／ 5s 这一类机子上有问题

**Comment by BrikerMan** [comment]
@dowhilenet 好像是的，我这没能重现。
