### ISSUE TITLE
Detect player PlayedToTheEnd in viewcontroller

### ISSUE THREAD

**Issue by mnizar** [BrikerMan/BMPlayer#33]
Swift 2.2 - release v0.3.3

how to get event in uiviewcontroller when video is PlayedToTheEnd ?

Thanks :)

**Comment by BrikerMan** [comment]
Swift 2.2 version is no longer maintain. You could fork and add codes to https://github.com/BrikerMan/BMPlayer/blob/master/BMPlayer/Classes/BMPlayer.swift .
I will add this delegate later to the Swift 3 version.
