### ISSUE TITLE
用于cell的player

### ISSUE THREAD

**Issue by jihongboo** [BrikerMan/BMPlayer#34]
我们的主播放器使用了你的项目，现在运行的情况非常好。
现在我们需要在一个tableview上使用播放器，目前的播放器UI对我们来说太复杂了，并且我尝试禁用panGesture但是无效。
能否提供隐藏UI和禁用panGesture的方法？

**Comment by BrikerMan** [comment]
嘿嘿，多谢认可。
你这个需求的话，直接使用 `BMPlayerLayerView` 然后通过 `BMPlayerLayerViewDelegate` 来获取各种回掉即可。在这个 view 上面再绘制你的控制 view。

**Comment by BrikerMan** [comment]
@jihongboo 怎么样了？

**Comment by jihongboo** [comment]
我重写了UI（其实就是把UI控件都隐藏了），另外去除了tap事件，现在运行良好，棒棒哒～

**Comment by kosicki123** [comment]
Can you provide any knowledge on how to use the fullscreen in the tableView or collectionView? I can successfully make it work in these ways, but not the fullscreen mode, can you help me? :)

**Comment by BrikerMan** [comment]
@kosicki123 You will need to use BMPlayerLayerView and customize whole functions by yourself. When u need to fullscreen, remove the view from table/collectionView and add to the window, then rotate the screen to fullscreen.

**Comment by kosicki123** [comment]
Thanks @BrikerMan. I'll try that!

**Comment by ibrahimzak** [comment]
@kosicki123 
did you find a way to fix your problem in fullscreen mode, may you please share the code

**Comment by kosicki123** [comment]
Hey @ibrahimzak it was 3 years ago. I can't remember. Sorry :/

**Comment by mapleleaf99** [comment]
@ibrahimzak 
did you find a way to fix your problem in fullscreen mode, may you please share the code
