### ISSUE TITLE
强制点击播放按钮崩溃

### ISSUE THREAD

**Issue by jihongboo** [BrikerMan/BMPlayer#35]
受限于网络原因，播放器UI已经加载完毕的情况下播放地址还没有获取到，此时强制点击播放按钮会崩溃
fileprivate func configPlayer(){
        self.playerItem = AVPlayerItem(url: videoURL)
 }
很明显此时videoURL为nil。
建议此处加一个判断。

**Comment by BrikerMan** [comment]
测试看看

**Comment by BrikerMan** [comment]
@jihongboo 给个反馈呗

**Comment by jihongboo** [comment]
已修复～摸摸哒
