### ISSUE TITLE
重装APP后AVPlayer不能播放缓存文件

### ISSUE THREAD

**Issue by mokai** [BrikerMan/BMPlayer#37]
尽管不是BMPlayer的问题，但还是想请教下~

把视频下载到Cache文件夹中缓存，然后播放，其它情况都是正常的，唯独APP重新安装后(覆盖安装)就播放不出来了，文件也还在，AVPlayer只进入ReadToPlay，调用play也不播放，duration也拿不到

**Comment by BrikerMan** [comment]
木有遇到过，不太清楚为啥。有试过直接用 `AVPlayer` 播放么？

**Comment by mokai** [comment]
已经解决了~，因为本地存储的绝对路径，而APP的Application UUID名称是会变的，所以导致重装后绝对路径无效了，不过不明白为什么路径不存在还会readToPlay。。。
