### ISSUE TITLE
切换源crash

### ISSUE THREAD

**Issue by jihongboo** [BrikerMan/BMPlayer#40]
更新了新版后，切换多个视频源会crash
if playerItem!.isPlaybackLikelyToKeepUp || playerItem!.isPlaybackBufferFull {
                self.state = .bufferFinished
            } else {
                self.state = .buffering
            }
这里不要强制解包playerItem，因为playerItem可能为nil。
另外视频播放完成后，播放按钮会时不时跳到暂停然后恢复，一直循环重复。

**Comment by BrikerMan** [comment]
@jihongboo 试试看

**Comment by jihongboo** [comment]
早！今天才发现这个页面是时时的，惊了

**Comment by jihongboo** [comment]
crash的问题解决了，但播放完成后播放按钮鬼畜的问题没有解决

**Comment by BrikerMan** [comment]
@jihongboo 再试试

**Comment by BrikerMan** [comment]
@jihongboo 给个消息呀

**Comment by jihongboo** [comment]
不好意思，我们公司的网太差，没办法第一时间更新。我刚测试了一下，播放按钮鬼畜的问题还是没有解决。。。另外loading出现的时机和实际播放的情况不对应，会出现视频加载完毕正在播放的时候liading仍旧未消失的问题。

**Comment by BrikerMan** [comment]
@jihongboo 确定用的最新版本吧，如果是我明天研究看看~

**Comment by BrikerMan** [comment]
@jihongboo one more try

**Comment by jihongboo** [comment]
今天更新了一下，之前的问题都解决了，棒棒哒～
