### ISSUE TITLE
Issue in landscape(full screen) in iPad

### ISSUE THREAD

**Issue by satyamub** [BrikerMan/BMPlayer#44]
Hi ,

Thanks for this good library. I tried this iPhones and its working good but in iPad, in Full screen or landscape, its not covering the full screen. Please help me.

**Comment by BrikerMan** [comment]
Don't have a iPad, will try on simulator. Will fix tomorrow~

**Comment by huadee** [comment]
It Support Ipad

**Comment by BrikerMan** [comment]
@satyamub with the right constraint, it will support full screen.
