### ISSUE TITLE
建议不要去掉全屏下返回按钮的回调

### ISSUE THREAD

**Issue by jihongboo** [BrikerMan/BMPlayer#45]
读了你的源码，全屏模式下，返回按钮的回调去掉了，可能是为了简化操作逻辑，避免返回事件同时应用到两种播放器状态下。但对于某些页面就单独一个全屏播放器而言，返回按钮可能还要处理其他事件（比如pop vc等）。因此建议backblock可以全模式使用，并且最好能把isFullScreen参数传过来，方便区分。

**Comment by BrikerMan** [comment]
这个主意不错，稍后就改。

**Comment by jihongboo** [comment]
对了，最好对block进行解包，避免block为nil 等情况

**Comment by jihongboo** [comment]
我改好了，你看下Pull request.
