### ISSUE TITLE
调节屏幕亮度没有动画

### ISSUE THREAD

**Issue by jumpingfrog0** [BrikerMan/BMPlayer#46]
调节屏幕亮度没有动画，音量就有，是和iOS10 有关？

**Comment by BrikerMan** [comment]
木有，音量是系统动画。亮度系统没有，我没有专门做这个。

**Comment by jumpingfrog0** [comment]
哦哦，我在ZFPlayer找到了方法，监听brightness，自己写一个BrightnessView。还有一个问题，怎么实现锁屏功能啊？

**Comment by BrikerMan** [comment]
没有加这个功能。
