### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by cedared** [BrikerMan/BMPlayer#5]
提个建议, 建议把controlview中的相关组件的权限设置为public 以便于用户可以自定义播放器样式

**Comment by BrikerMan** [comment]
@cedared 我之前的想法是做一个协议，然后用户给我提供一个实现该协议所有要求的view来自定义UI。正在构思一个比较方便的方案。

**Comment by cedared** [comment]
@BrikerMan 好的~

**Comment by BrikerMan** [comment]
@cedared 有什么更好的建议么？

**Comment by BrikerMan** [comment]
@cedared https://eliyar.biz/custom-player-ui-with-bmplayer/ 支持了自定义UI
