### ISSUE TITLE
重新播放按钮显示异常

### ISSUE THREAD

**Issue by AlleluiaCN** [BrikerMan/BMPlayer#52]
1.视频播放结束后出现重播按钮，然后点击隐藏mainMaskView，重播按钮会跟着隐藏，然后点击显示mainMaskView时重播按钮已经没了。
2.视频播放结束后出现重播按钮，然后通过点击左下方的播放按钮来播放，重播按钮还会一直显示在中间

**Comment by BrikerMan** [comment]
现在还有么？

**Comment by Owl7** [comment]
这问题一直都有啊！

**Comment by BrikerMan** [comment]
近期重构，争取修复这些遗留问题

**Comment by BrikerMan** [comment]
update to 0.8.0 to fix this issue
