### ISSUE TITLE
Full screen issue

### ISSUE THREAD

**Issue by mukulm24** [BrikerMan/BMPlayer#54]
When i full screen the player the view doesn't come full screen and the controls for slow motion are not seen.

**Comment by BrikerMan** [comment]
Please provide more detail, screenshot or demo

**Comment by RaziPour1993** [comment]
When i full screen the player the view doesn't come full screen and the controls for slow motion are not seen.

![img_1395-11-25 15 50 42](https://cloud.githubusercontent.com/assets/16708111/22883184/30e7824a-f204-11e6-9135-17a92d3d5d08.jpg)

and when mute iphone not sound bmplayer

**Comment by RaziPour1993** [comment]
How Disable full screen when rotate?

**Comment by BrikerMan** [comment]
@RaziPour1993  Please check your AutoLayout constraints with [Reveal](http://www.revealapp.com/)

**Comment by ducnmisbk** [comment]
> When i full screen the player the view doesn't come full screen and the controls for slow motion are not seen.
> 
> ![img_1395-11-25 15 50 42](https://cloud.githubusercontent.com/assets/16708111/22883184/30e7824a-f204-11e6-9135-17a92d3d5d08.jpg)
> 
> and when mute iphone not sound bmplayer

You should update the height constraint when rotate to landscape.
```
override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        super.viewWillTransition(to: size, with: coordinator)
        ...
        player.snp.updateConstraints() { (make) in
            ...
            make.height.equalTo(playerHeight).multipliedBy(1.0).priority(750)
        }
    }
```
