### ISSUE TITLE
这个视频只有声音没有画面，请问是什么原因？？

### ISSUE THREAD

**Issue by miws** [BrikerMan/BMPlayer#55]
http://cntv.vod.cdn.myqcloud.com/flash/mp4video40/TMS/2015/03/17/29f9f25a356a4e58bc1514e8c3b3e6e1_h264418000nero_aac32-9.mp4
这是cntv的视频，使用bmplayer播放只有声音，没有画面

**Comment by BrikerMan** [comment]
可以播放呀~ 升级到 `0.8.0` 看看。

**Comment by danmingyang** [comment]
播放本地视频的时候也遇到了
