### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by hdoria** [BrikerMan/BMPlayer#6]
Could you add support for Carthage?

**Comment by BrikerMan** [comment]
@hdoria ok. I will try this weekend.

**Comment by adrianodiasx93** [comment]
@BrikerMan any luck?

**Comment by BrikerMan** [comment]
@adrianodiasx93 @hdoria working

**Comment by BrikerMan** [comment]
@hdoria @adrianodiasx93 done~
