### ISSUE TITLE
playTimeDidChange

### ISSUE THREAD

**Issue by RaziPour1993** [BrikerMan/BMPlayer#60]
Hi 
I need change time "playTimeDidChange" to millisecond from second.
please help me.

**Comment by BrikerMan** [comment]
Please chech [The Swift Programming Language](https://developer.apple.com/library/prerelease/content/documentation/Swift/Conceptual/Swift_Programming_Language/TheBasics.html#//apple_ref/doc/uid/TP40014097-CH5-ID309) to learn the basic of swift.
```
let sec = Int(currentTime)
```
