### ISSUE TITLE
BMPlayer not playing video is slide the tracker

### ISSUE THREAD

**Issue by mukulm24** [BrikerMan/BMPlayer#61]
if i press play button video doesnt get played. If I write bmPlayer.play() and call that function then it is player else bmPlayer doesnot play.
Version used :
pod 'BMPlayer', '~> 0.3.3'

**Comment by BrikerMan** [comment]
The latest release is 0.7.1. Please update.
```
pod 'BMPlayer', '~> 0.7.1'
```

**Comment by mukulm24** [comment]
i want to use it for swift 2.2

**Comment by BrikerMan** [comment]
Then you have to fix this by yourself, sorry.
