### ISSUE TITLE
全屏的时候,只有状态栏是横屏的,控制器的视图还是竖屏

### ISSUE THREAD

**Issue by manajay** [BrikerMan/BMPlayer#62]
我的项目中锁定大部分页面为竖屏,只允许屏幕在个别的控制器中是 横屏
测试 这个Demo是没有问题,但是我项目中锁定竖屏后,就不可以了.

**Comment by BrikerMan** [comment]
这个不是播放器问题，是控制器设定问题，请参考。
1. https://eliyar.biz/ios-manual-change-screen-orientation/
2. https://lvwenhan.com/ios/458.html

**Comment by manajay** [comment]
谢谢 已经解决了问题,处理好项目中的 根控制器中有关横屏有关的代码 就好了
