### ISSUE TITLE
Detecting when a stream connection is lost

### ISSUE THREAD

**Issue by bluemix** [BrikerMan/BMPlayer#63]
Hello dear,
how can I know if a connection is lost in the middle of the stream?
for example, when playing a video, and at certain time point, the devices disconnected.

is there any observer or notification that is known for this purpose in AVPlayer?
thanks in advance.

![simulator screen shot feb 27 2017 18 59 18](https://cloud.githubusercontent.com/assets/3332274/23368628/844eb518-fd1f-11e6-811a-9fb341e113b8.png)

**Comment by jihongboo** [comment]
You can use Reachability which can observe the reachability of network, including the situation of your question.

**Comment by bluemix** [comment]
ah, ok, thanks a lot :)

**Comment by BrikerMan** [comment]
@jihongboo is correct. You could use Reachability to observe network status~
