### ISSUE TITLE
cntv视频资源是可以播放,但没有画面,只有声音.

### ISSUE THREAD

**Issue by miws** [BrikerMan/BMPlayer#65]
之前的版本就是这样的,现在升级到最新的8.1还一样没有解决问题
http://cntv.vod.cdn.myqcloud.com/flash/mp4video40/TMS/2015/03/17/29f9f25a356a4e58bc1514e8c3b3e6e1_h264418000nero_aac32-9.mp4
这是cntv的视频，使用bmplayer播放只有声音，没有画面

**Comment by BrikerMan** [comment]
https://github.com/BrikerMan/BMPlayer/blob/master/Example/BMPlayer/VideoPlayViewController.swift#L70 你看看 Demo 吧， Demo 就是播放这个视频，没问题。

**Comment by miws** [comment]
好吧, 我的apple账号到期了 没法在真机上测试,在模拟器里 你的其他几个视频都有画面, 就是这个cntv的视频没有画面,只有声音,不知是什么原因.

**Comment by BrikerMan** [comment]
确实模拟器有问题，不知道为什么。但是真机没问题~
