### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by AdeelNoor17** [BrikerMan/BMPlayer#67]
Hi, 

I have implemented Bmplayer and its perfect for my app requirements. But i need to implement more features like subtitles, is there any way to show subtitles of video on Bmplayer.

Thanks for help

**Comment by BrikerMan** [comment]
There are 3 ways to get this done.

1. Use `BMPlayerLayer` and create you own player with control UI.
2. Use `BMPlayerCustomControlView ` to create your customized control UI, not recommend. I created `BMPlayerCustomControlView` to allow user to customize UI easily, but it makes thing worse.
3. Give me the UI you needs, and I help you add this function.

**Comment by AdeelNoor17** [comment]
<img width="350" alt="screen shot 2017-03-30 at 10 25 04 pm" src="https://cloud.githubusercontent.com/assets/19529360/24517453/cf67c892-1597-11e7-9be9-856ce0896fe0.png">


Attached is the screenshot of my video that needs subtitles. Its in the UITableView actually. I need to add label slightly top of seekbar. I have the .srt file as well.

**Comment by BrikerMan** [comment]
Understood what you need, let me try to add this function~

**Comment by BrikerMan** [comment]
check the latest demo, tell me is that works fine for u.
```
let strURL = Bundle.main.url(forResource: "SubtitleDemo", withExtension: "srt")!

let subtitle = BMSubtitles(url: strURL)

let asset = BMPlayerResource(name: "Video Name Here",
                             definitions: [BMPlayerResourceDefinition(url: videoURL, definition: "")],
                             cover: nil,
                             subtitles: subtitle)
```

**Comment by BrikerMan** [comment]
@AdeelNoor17 is that working?

**Comment by a-radwan** [comment]
Does it supports a subtitles with remote URL, not local resource?

**Comment by BrikerMan** [comment]
@a-radwan yes, support remote srt file.

**Comment by a-radwan** [comment]
Can u please check this issue, 
https://github.com/BrikerMan/BMPlayer/issues/217

**Comment by kushalmaniyar** [comment]
Hello Team, 

I have srt format of URL 
https://appdeveloper.yuvtv.com/filestore/2/2/2/7_c0af593db64adf5/2227_alt_4953_c6e477199558a4c.srt

`       let subtitle = BMSubtitles(url: subTitleURL!)
        let asset = BMPlayerResource(name: "Video Name Here",
        definitions: [BMPlayerResourceDefinition(url: playerUrl, definition: "")],
        cover: nil,
        subtitles: subtitle)`

it shows me subtitle together instead of the video frames. 

![Simulator Screen Shot - iPhone 8 - 2020-06-17 at 12 54 48](https://user-images.githubusercontent.com/16156294/84870902-7eaf6780-b09d-11ea-8383-7fb16a5e8cf1.png)

can you please let me know how to show subtitle frame wise?

**Comment by BrikerMan** [comment]
@kushalmaniyar it seems BMPlayer failed to parse the subtitle file into the correct format, AKA the Group objects.
you might check out this function to determine why it failed to parse. 
https://github.com/BrikerMan/BMPlayer/blob/e37be9e0b73f8ff5d1fc5991d95518342cbc80d4/Source/BMSubtitles.swift#L85

**Comment by kushalmaniyar** [comment]
Hello @BrikerMan ,
Thank you for the prompt update. do you have any sample srt file so I can compare it with my file? 

I have debugged the group and, the first iteration it gets whole data.

**Comment by BrikerMan** [comment]
> Hello @BrikerMan ,
> Thank you for the prompt update. do you have any sample srt file so I can compare it with my file?
> 
> I have debugged the group and, the first iteration it gets whole data.

https://github.com/BrikerMan/BMPlayer/tree/master/Example/Resource

**Comment by kushalmaniyar** [comment]
Hello @BrikerMan 

Thank you for your suggestion, I have to change the parsing by 
`scanner.scanUpTo("\n\n", into: &textString)`
instead of 
`scanner.scanUpTo("\r\n\r\n", into: &textString)`

it works as expected. 

Can you please let me know how to change subtitle in a running video?

`delay(5, completion: {
    if let resource = self.player.currentResource {
        resource.subtitle = nil
        self.player.forceReloadSubtile()
    }
})`

I have checked this but couldn't find currentResource in latest repository. 

can you please let me know about change the subtitle?

Thanks 
Kushal

**Comment by BrikerMan** [comment]
> Hello @BrikerMan
> 
> Thank you for your suggestion, I have to change the parsing by
> `scanner.scanUpTo("\n\n", into: &textString)`
> instead of
> `scanner.scanUpTo("\r\n\r\n", into: &textString)`
> 
> it works as expected.
> 
> Can you please let me know how to change subtitle in a running video?
> 
> `delay(5, completion: { if let resource = self.player.currentResource { resource.subtitle = nil self.player.forceReloadSubtile() } })`
> 
> I have checked this but couldn't find currentResource in latest repository.
> 
> can you please let me know about change the subtitle?
> 
> Thanks
> Kushal

@birdmichael can you help with this issue?

**Comment by birdmichael** [comment]
@kushalmaniyar 
[update](https://github.com/BrikerMan/BMPlayer/pull/308/commits/565c1ad925a6ee97d35325b91fb42bd7061f2e72)

1. Add `func update (subtitles: BMSubtitles?)` to change the subtitle interface to support multilingual subtitles.
2. `BMSubtitles` add `delay`, support dynamic modification of subtitle timeline during playback

**Comment by kushalmaniyar** [comment]
Thank you for the update @BrikerMan , it works as expected.

Is there any way to remove subtitles? I tried below. it stops updating subtitle but the last subtitle remains in UI

`self.player.playerView?.resource?.subtitle = nil`

**Comment by BrikerMan** [comment]
maybe this will work.
```
self.player.update(subtitles: nil)
```

**Comment by kushalmaniyar** [comment]
If there is already subtitle on screen, it will just stay there.

![Simulator Screen Shot - iPhone 8 - 2020-06-18 at 14 49 55](https://user-images.githubusercontent.com/16156294/85003736-3dd65200-b174-11ea-8ba8-724cac5561d4.png)

**Comment by BrikerMan** [comment]
```
self.player.update(subtitles: nil)
self.player. controlView.subtitleBackView.isHidden = true
```

**Comment by kushalmaniyar** [comment]
It works. Thank you for the prompt update.

**Comment by BrikerMan** [comment]
> It works. Thank you for the prompt update.

No worries, after merging the #309 into next release, you will be no longer need to call 

```swift
self.player.controlView.subtitleBackView.isHidden = true
```
