### ISSUE TITLE
Discussion: An easy way to customize control UI

### ISSUE THREAD

**Issue by BrikerMan** [BrikerMan/BMPlayer#68]
I created BMPlayerCustomControlView to allow users to customize UI easily, but it makes thing worse. 
I am planning to refactor the whole player to allow the user easily customize the control UI. There are several ideas:

1. create a `BMPlayerControlView` and allow the user to subclass and change the Auto-layout and icon images to customize UI.
2. use the `BMPlayerCustomControlView` to customize and simplify the protocol.

**Comment by benbahrenburg** [comment]
I heavily use the BMPlayerCustomControlView.  I think allowing for a subclass would provide the most flexibility.

**Comment by BrikerMan** [comment]
@benbahrenburg I am already working on it, and planning to finish by tomorrow if I can. But this will break your code. I chose the second option to create a control view which allows user to subclass and change rather than protocol with message variable and function. Is that ok with you? And I have already add a subtitle function that allows user to show their str subtile with the video.

**Comment by benbahrenburg** [comment]
@BrikerMan sounds good.  Will the default implementation use the same protocol?  Figured provides the best documentation as we can just look at the default implementation to see how to implement our own.

**Comment by BrikerMan** [comment]
Yes, will provide document and Example~

**Comment by BrikerMan** [comment]
@Owl7 @benbahrenburg Try the latest commit and the example. This is custom example `BMPlayerCustomControlView`.

**Comment by BrikerMan** [comment]
@csauvage Check the `Custom Control UI 2`. Just committed.

**Comment by benbahrenburg** [comment]
@BrikerMan works perfectly.  Thanks for doing this.

**Comment by BrikerMan** [comment]
@benbahrenburg could you help me submit BMPlayer to https://github.com/matteocrippa/awesome-swift?

**Comment by benbahrenburg** [comment]
@BrikerMan ok, will do tomorrow

**Comment by benbahrenburg** [comment]
@BrikerMan can you do me a favor and slightly update the project description. The awesome swift list has a requirement that the project description doesn't say "Description does not say "written in Swift" or variant "

I would suggest "A video player for iOS, based on AVPlayer, support the horizontal, vertical screen. support adjust volume, brigtness and seek by slide."

**Comment by BrikerMan** [comment]
@benbahrenburg ok~

**Comment by benbahrenburg** [comment]
@BrikerMan https://github.com/matteocrippa/awesome-swift/pull/905

**Comment by benbahrenburg** [comment]
@BrikerMan PR merged https://github.com/matteocrippa/awesome-swift/pull/905#event-1054093911
