### ISSUE TITLE
使用 BMPlayerLayer 制控制 UI 和逻辑。

### ISSUE THREAD

**Issue by Owl7** [BrikerMan/BMPlayer#69]
作者你好，可不可以在博客里出个使用 BMPlayerLayer 自己定制控制 UI 和逻辑的博文？

**Comment by BrikerMan** [comment]
好的，我也在想办法做一个比较方便简单的 UI 定制方案。参见 #68。有什么好的意见建议可以提出来。

**Comment by Owl7** [comment]
现在要自定义UI和逻辑感觉好麻烦的。

**Comment by BrikerMan** [comment]
是的，太复杂了。

**Comment by BrikerMan** [comment]
在准备重构 controlview 然后你们只需要 `subclass` 然后重写具体按钮的布局方法。
