### ISSUE TITLE
Remove some dependencies

### ISSUE THREAD

**Issue by hdoria** [BrikerMan/BMPlayer#7]
Is there a way to make BMPlayer work without some of these dependencies:

Using Reveal-iOS-SDK (1.6.2)
Using SnapKit (0.20.0)
Using SwipeBack (1.1.0)

SwipeBack is obj-c and can mess some gestures. :( I don't see any problem with SnapKit or Reveal although.

**Comment by BrikerMan** [comment]
@hdoria it is work fine without SwipeBack and Reveal-iOS-SDK. It only for the demo. Just add BMPlayer to your pod file. that works fine.
