### ISSUE TITLE
how can I update Video to play（change ） ,in case I do not quit current controller

### ISSUE THREAD

**Issue by wenlanhuitai** [BrikerMan/BMPlayer#71]
I ran into a problem : 
 
first Come in controller, and set BMPlayerResource  - > self.player.setVideo(resource: asset) then worked wonderful.

But ,then I want to change Video Info to play ( pause() - > change BMPlayerResource  - > setVideo agin)，but the player Still playing the video before ！

who can help me ？ How to change video to play  in case I do not quit current controller ？

**Comment by BrikerMan** [comment]
Please check out the Demo and check is that fixed, if so I will release new version to CocoaPods

**Comment by wenlanhuitai** [comment]
change Video it worked！  
But the fullScreen can not work in my project（your demo is OK），My project  Player Controller view On the window  ， like this ： window.addSubview(self.playVC.view)
In addition ， definitions switch button can not show  when Vertical screen

**Comment by BrikerMan** [comment]
You should check this demo to understand the Screen orient change process, It is related to your project and controller settings. And the definitions button is designed not show Vertical screen.
