### ISSUE TITLE
change video to play , the Before video`s  voice is still in play

### ISSUE THREAD

**Issue by wenlanhuitai** [BrikerMan/BMPlayer#73]
My player controller is hold by root viewController and view is added on the window ，（scale reduce in  the lower right corner of window）

Because has remained the play viewController，so the VC will  never not be die, then I tap different cell of video，root View controller will Notify the PlayVc to change “BMPlayerResource” ，the new video can play well ，but the before video`s voice ， if change third，there will be two voice before， if  change fourth ， there will  be three voice before..... is seems that The voice never die Before switching.

I can not find the solution，I even doubt that my project design is wrong ？！

**Comment by wenlanhuitai** [comment]
http://i2.muimg.com/4851/0946b56f8200150a.jpg    

this is my design draw.

**Comment by BrikerMan** [comment]
I do have a similar design. I think the problem it how you implemented it.
Will discuss details with u tomorrow. I suggest to use BMPlayerLayer with
custom player control UI and design the player as a singleton so that
always only one player exists.
YinChao Xie <notifications@github.com>于2017年4月3日 周一上午12:28写道：

**Comment by wenlanhuitai** [comment]
Thank you for your patience reply, the play VC never die， because of holding by rootViewController, so the BMPlayer is just one. 

Good night...See you tomorrow

**Comment by BrikerMan** [comment]
@wenlanhuitai check this, I created the demo and it works fine. Maybe because I have not released the latest commit to CocoaPods, so your version is not working. try
```ruby
pod 'BMPlayer', :git => 'https://github.com/BrikerMan/BMPlayer.git'
```

**Comment by wenlanhuitai** [comment]
tanks，I try.
