### ISSUE TITLE
Add caching support

### ISSUE THREAD

**Issue by Owl7** [BrikerMan/BMPlayer#79]
@BrikerMan 我看播放视频的时候有个缓存进度，可是我没找到缓存文件。 我想问一下有缓存文件吗？能播放缓存文件不？我想下次进入的时候直接播放缓存文件，而不是每次进入的时候从新再缓存一次。

**Comment by BrikerMan** [comment]
缓存功能目前还没加，这一块比较复杂，目前可以看看下面两篇。等有空了实现一下。
1. [iOS音视频实现边下载边播放](http://sky-weihao.github.io/2015/10/06/Video-streaming-and-caching-in-iOS/)
2. [http://www.jianshu.com/p/990ee3db0563](http://www.jianshu.com/p/990ee3db0563)

**Comment by Owl7** [comment]
好的，谢谢了。

**Comment by Hamasn** [comment]
yes, exactlly, need a cache feature, that such a good player should have.

**Comment by BrikerMan** [comment]
add the cache function with VIMediaCache, use `pod 'BMPlayer/CacheSupport'` to try that out~

**Comment by chhaysotheara** [comment]
Cache support is just a test version right ? can I use it for official project? I have already try and test it and i love it.

**Comment by BrikerMan** [comment]
@chhaysotheara I just released the 0.8.6 version with the cache support, but, it is still testing and I cannot promise it will work fine. If you have tested and It works fine, I think it is ok to use in official project. The caching is based of https://github.com/vitoziv/VIMediaCache.

**Comment by satishVekariya** [comment]
Reference for caching swift code with cache management https://github.com/VeinGuo/VGPlayer
