### ISSUE TITLE
NVAcitivityIndicator continues showing after buffering is complete on iOS 10

### ISSUE THREAD

**Issue by thetravischannel** [BrikerMan/BMPlayer#8]
Tested against iPad Air 2, iPhone 6, and 5s, along with three different video sources. After the video loads and buffering is complete, the instance of NVActivityIndicator continues animating within the player.

**Comment by BrikerMan** [comment]
@thetravischannel did you try with the Example project? I try it on iOS 10 beta 3 (14A5309d). It worked just fine.

**Comment by thetravischannel** [comment]
@BrikerMan I circled back around and tested with the test project on an iOS 10 device, and it seems that the issue only affects HLS streams, and not static media files. When pointed at an m3u8 playlist, the NVActivityIndicator continues to spin while playing. This may be an issue with playbackLikelyToKeepUp in AVPlayer with HLS streams on iOS 10, rather than BMPlayer.

**Comment by BrikerMan** [comment]
@thetravischannel good to know, thanks for the detail.

**Comment by kushalhyperlink** [comment]
Hello Team - is there any update to play HLS stream?
