### ISSUE TITLE
 init from storyboard,then I can not use custom controlUI

### ISSUE THREAD

**Issue by wenlanhuitai** [BrikerMan/BMPlayer#81]
If my player init from storyboard,then I can not use custom controlUI

    required public init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        initUI()
        initUIData()
        configureVolume()
        preparePlayer()
    }
    
    public convenience init (customControllView: BMPlayerControlView?) {
        self.init(frame:CGRect.zero)
        self.customControllView = customControllView
        initUI()
        initUIData()
        configureVolume()
        preparePlayer()
    }
    fileprivate var customControllView: BMPlayerControlView?

beacuse the  customControllView is  private .

I  advice the var “customControllView” set public .

**Comment by BrikerMan** [comment]
I don't think this will fix the problem. custom control UI will add to subviews at `func initUI()`. And it will call at `public init?(coder aDecoder: NSCoder)`. If you changed the control ui after this process, it will not added to the player view.

**Comment by wenlanhuitai** [comment]
thanks！
