### ISSUE TITLE
App crashing on start-up on some devices. 

### ISSUE THREAD

**Issue by shashanit** [BrikerMan/BMPlayer#83]
Hi, my application is working fine on some devices but on some its crashing and here's the screenshot of the crash report. 

[Imgur Screenshot](http://i.imgur.com/us3DffL.png)

**Comment by BrikerMan** [comment]
I need more details about this bug. Please provide me with the player version, how did you added to the project.

**Comment by shashanit** [comment]
0.7.1 -- I simply installed it through " pod 'BMPlayer' ". It doesnt crash for some devices but for most of them, its crashing

**Comment by BrikerMan** [comment]
It will not crash on debug mode right?

**Comment by shashanit** [comment]
Yes it doesn't crash on simulator but on device it does, I just fixed that. What one needs to do is clear the default run path from build setting then from general tab -> Add BMplayer framework to embedded binaries and then build.

Otherwise for half devices of the devices it works and for other half it doesn't. Totally random.

**Comment by shashanit** [comment]
Yes it doesn't crashes on the debug mode but crashes on the device : /

**Comment by BrikerMan** [comment]
Is that fixed now? By add BMplayer framework to embedded binaries.
