### ISSUE TITLE
I find a bug: 

### ISSUE THREAD

**Issue by wenlanhuitai** [BrikerMan/BMPlayer#86]
the raw code  , It has A circular reference （when I pop current play VC ，the function always called 
 forever）: 

 open func autoFadeOutControlViewWithAnimation() {
        cancelAutoFadeOutAnimation()
        delayItem = DispatchWorkItem {
            self.controlViewAnimation(isShow: false)
        }
        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + BMPlayerConf.animateDelayTimeInterval,
                                      execute: delayItem!)
    }

I change ， It can release well ：

open func autoFadeOutControlViewWithAnimation() {
        cancelAutoFadeOutAnimation()
        **weak var  weakSelf = self**
        delayItem = DispatchWorkItem {
            **weakSelf?.**controlViewAnimation(isShow: false)
        }
        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + BMPlayerConf.animateDelayTimeInterval,
                                      execute: delayItem!)
    }

**Comment by BrikerMan** [comment]
Thanks for your feedback, fixed~
