### ISSUE TITLE
锁定屏幕的方向 点击旋转全屏按钮无效

### ISSUE THREAD

**Issue by SugarAlex** [BrikerMan/BMPlayer#87]
我把app的方向调成只是竖屏的 进入播放后点击全屏播放不会旋转
LZ用KVC监听吧 锁定后就收不到通知了 没法旋转了就

**Comment by BrikerMan** [comment]
项目设定中锁定后任何办法都不能旋转屏幕的，请参照 https://eliyar.biz/ios-manual-change-screen-orientation/
