### ISSUE TITLE
Carthage build error

### ISSUE THREAD

**Issue by aloveric** [BrikerMan/BMPlayer#88]
*** Fetching BMPlayer
*** Fetching NVActivityIndicatorView
*** Fetching SnapKit
*** Checking out NVActivityIndicatorView at "3.6.1"
*** Checking out SnapKit at "3.2.0"
*** Checking out BMPlayer at "0.8.4"
*** xcodebuild output can be found in /var/folders/b0/nt3z_8vd4m13qvlwfjbsg3gdc2q8gx/T/carthage-xcodebuild.rgoLCV.log
*** Building scheme "NVActivityIndicatorView" in NVActivityIndicatorView.xcodeproj
*** Building scheme "SnapKit" in SnapKit.xcworkspace
*** Building scheme "BMPlayer" in BMPlayer.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project "/Users/xxx/Documents/Xcode Source/SplashVideo/Carthage/Checkouts/BMPlayer/BMPlayer.xcodeproj" -scheme BMPlayer -configuration Release -derivedDataPath /Users/xxx/Library/Caches/org.carthage.CarthageKit/DerivedData/BMPlayer/0.8.4 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/b0/nt3z_8vd4m13qvlwfjbsg3gdc2q8gx/T/carthage-xcodebuild.rgoLCV.log

**Comment by aloveric** [comment]
![screen shot 2017-04-23 at 4 16 44 pm](https://cloud.githubusercontent.com/assets/8198881/25312002/4af81434-2840-11e7-871c-73b56ecef14c.png)
![Uploading Screen Shot 2017-04-23 at 4.16.20 PM.png…]()

**Comment by aloveric** [comment]
应该是找不到文件

Caches/org.carthage.CarthageKit/DerivedData/BMPlayer/0.8.4/Build/Intermediates/BMPlayer.build/Release-iphoneos/BMPlayer.build/unextended-module-overlay.yaml -Xcc -working-directory/Users/xxx/Documents/Xcode\ Source/SplashVideo/Carthage/Checkouts/BMPlayer
<unknown>:0: error: no such file or directory: '/Users/xxx/Documents/Xcode Source/SplashVideo/Carthage/Checkouts/BMPlayer/BMPlayer/Classes/BMPlayerItem.swift'
<unknown>:0: error: no such file or directory: '/Users/xxx/Documents/Xcode Source/SplashVideo/Carthage/Checkouts/BMPlayer/BMPlayer/Classes/BMPlayerManager.swift'
<unknown>:0: error: no such file or directory: '/Users/xxx/Documents/Xcode Source/SplashVideo/Carthage/Checkouts/BMPlayer/BMPlayer/Classes/BMSubtitles.swift'
<unknown>:0: error: no such file or directory: '/Users/xxx/Documents/Xcode Source/SplashVideo/Carthage/Checkouts/BMPlayer/BMPlayer/Classes/BMPlayerProtocols.swift'
<unknown>:0: error: no such file or directory: '/Users/xxx/Documents/Xcode Source/SplashVideo/Carthage/Checkouts/BMPlayer/BMPlayer/Classes/BMPlayerLayerView.swift'
<unknown>:0: error: no such file or directory: '/Users/xxx/Documents/Xcode Source/SplashVideo/Carthage/Checkouts/BMPlayer/BMPlayer/Classes/BMPlayerControlView.swift'
<unknown>:0: error: no such file or directory: '/Users/xxx/Documents/Xcode Source/SplashVideo/Carthage/Checkouts/BMPlayer/BMPlayer/Classes/BMPlayer.swift'
<unknown>:0: error: no such file or directory: '/Users/xxx/Documents/Xcode Source/SplashVideo/Carthage/Checkouts/BMPlayer/BMPlayer/Classes/BMPlayerClearityChooseButton.swift'
<unknown>:0: error: no such file or directory: '/Users/xxx/Documents/Xcode Source/SplashVideo/Carthage/Checkouts/BMPlayer/BMPlayer/Classes/BMTimeSlider.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

** BUILD FAILED **

**Comment by BrikerMan** [comment]
fixed at 0.8.5~

**Comment by aloveric** [comment]
Thanks for quick response :)
