### ISSUE TITLE
Replay local video error

### ISSUE THREAD

**Issue by aloveric** [BrikerMan/BMPlayer#89]
播放本地文件时，如果选择画面中的replay图标，重放时会一直显示这个图标。点击进度条的播放正常.

**Comment by BrikerMan** [comment]
什么版本？是否是最新版？

**Comment by aloveric** [comment]
对的亲，是最新版本。刚修复了我提交的一个issue：https://github.com/BrikerMan/BMPlayer/issues/88 后，我编译demo试过发现的。

**Comment by BrikerMan** [comment]
ok, 一直试用的网络文件，一会试试本地文件。

**Comment by aloveric** [comment]
恩，多谢。本地文档前后倒带的时候，那个屏幕中间的时间也会有点延时消失。

**Comment by aloveric** [comment]
@BrikerMan 稍后我试试看，谢谢修复~~
