### ISSUE TITLE
有个建议，增加一个缓存功能

### ISSUE THREAD

**Issue by DaokunBai** [BrikerMan/BMPlayer#91]
可以参照 https://github.com/vitoziv/VIMediaCache

**Comment by BrikerMan** [comment]
谢谢建议，已经计划，近期抽空完成~。
问题重复了：#79。

**Comment by DaokunBai** [comment]
嗯 上面的那个框架已经实现了缓存功能，不过是 OC 版本的，swift 也可以用，不过需要进入 BMPlayer 内部修改两行代码，我是用 pod 管理的，这样每次更新都需要去修改，有些麻烦。

**Comment by BrikerMan** [comment]
Added the cache function with VIMediaCache, use pod 'BMPlayer/CacheSupport' to try that out~ @DaokunBai
