### ISSUE TITLE
How to fill the video image is adjusted for full screen play？

### ISSUE THREAD

**Issue by wenlanhuitai** [BrikerMan/BMPlayer#92]
How to fill the video image is adjusted for full screen play （play layer rotate ）
like this：
<img src='http://i4.buimg.com/1949/76a410be14399a0f.jpg'>

**Comment by BrikerMan** [comment]
Check the `Custom Control UI` for the demo~ Is this what u wanted?

**Comment by wenlanhuitai** [comment]
I try Again， but still get a error problem  ：
this is the  screenshots：
http://i2.muimg.com/1949/1e69f41192e9da1e.jpg

**Comment by wenlanhuitai** [comment]
It`s my mistake ， I  opened error .xcworkspace file , thanks!
