### ISSUE TITLE
No Such Module for NVActivityIndicatorView and BMPlayer

### ISSUE THREAD

**Issue by xbomber360** [BrikerMan/BMPlayer#94]
Hello,
after download the latest version of your project i run pod install located in **BMPlayer-master/Example**  . It run correctly without errors but when I open the example project the build fail because xcode doesn't fine the two module that I described in the issue object. I used the last version of cocoa pods. Could you help me ?
I report some screenshot
![pod_install1](https://cloud.githubusercontent.com/assets/7620002/25785686/42ef7578-3387-11e7-9c15-66d5741d118f.png)
![pod_install2](https://cloud.githubusercontent.com/assets/7620002/25785687/43c42e1c-3387-11e7-95f9-8ea36d00c7c6.png)
![pod_install3](https://cloud.githubusercontent.com/assets/7620002/25785688/457dbc6e-3387-11e7-8e38-a35fdcbd01c6.png)
![example project](https://cloud.githubusercontent.com/assets/7620002/25785689/49823c0e-3387-11e7-8e12-9cdcff49bc98.png)

**Comment by BrikerMan** [comment]
Just clean and re-build the project~

**Comment by xbomber360** [comment]
I clean ad rebuild project but Xcode doesn't find the modules. After pod install should  modules appear in Frameworks folder with toolbox icon? I can add its manually ?

**Comment by BrikerMan** [comment]
What is your cocoapods version?

**Comment by xbomber360** [comment]
My version is 1.2.1

**Comment by xbomber360** [comment]
there is a method to include manually the required dependencies ?

**Comment by MangoMade** [comment]
@xbomber360 to run example, you should open BMPlayer/Example/BMPlayer.xcworkspace

cannot open BMPlayer/BMPlayer.xcodeproj and run directly.

**Comment by BrikerMan** [comment]
@MangoMade Thanks, I ignored this problem. You should use xcworkspace when you are using Cocoapods.

**Comment by xbomber360** [comment]
thanks @MangoMade and @BrikerMan Opening the  BMPlayer/Example/BMPlayer.xcworkspace I can run correctly the example
